{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.auscybernix.programs.sketchybar;
in
{

  options.auscybernix.programs.sketchybar = {

    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
    };
  };

  config = lib.mkIf cfg.enable {

    # generate colors file from stylix config
    home.packages = with pkgs; [
      yq
      jq
    ];
    home.file."${config.auscybernix.flakeConfig.flakeFolder}/.config/sketchybar/colors.sh" = {
      text =
        let
          colors = config.stylix.base16Scheme;
        in
        ''
          #!/bin/bash
          # this file is generated by stylix, do not edit
          export COLOR_BACKGROUND='${colors.base00}'
          export COLOR_BLACK='${colors.base01}'
          export COLOR_SELECTION='${colors.base02}'
          export COLOR_COMMENT='${colors.base03}'
          export COLOR_DARKGRAY='${colors.base04}'
          export COLOR_FOREGROUND='${colors.base05}'
          export COLOR_BRIGHTWHITE='${colors.base06}'
          export COLOR_WHITE='${colors.base07}'
          export COLOR_RED='${colors.base08}'
          export COLOR_ORANGE='${colors.base09}'
          export COLOR_YELLOW='${colors.base0A}'
          export COLOR_GREEN='${colors.base0B}'
          export COLOR_CYAN='${colors.base0C}'
          export COLOR_BLUE='${colors.base0D}'
          export COLOR_MAGENTA='${colors.base0E}'
          export COLOR_BROWN='${colors.base0F}'
        '';
    };
    home.file.".config/sketchybar" = {
      source = config.lib.file.linkLocalPath ../../../../.config/sketchybar;
      #    recursive = true;
    };
    programs.sketchybar = {
      service.enable = true;
      enable = true;
      extraPackages = with pkgs; [
        jq
        yq
        yabai
        nowplaying-cli
      ];
    };
  };

}
