#!/usr/bin/env bash

fg_c() {
    tput setaf $1
}
bg_c(){
    tput setab $1
}
fg_t(){
    echo -en "\x1b[38;2;$1;$2;$3""m"
}
bg_t(){
    echo -en "\x1b[48;2;$1;$2;$3""m"
}


BOLD=$(tput bold)
ITALIC=$(tput sitm)
BLACK=239
WHITE=15


B_BG=$(bg_c $BLACK)
B_FG=$(fg_c $BLACK)
NORMAL=$(tput sgr0)
W_BG=$(bg_c $WHITE)
W_FG=$(fg_c $WHITE)

if apt --help  1> /dev/null 2>&1
    then
        package_manager="apt"
        packages=$(apt list --installed 2> /dev/null | wc -l)
elif nixos-rebuild --help 2>&1 1> /dev/null 
    then
    packages=$(cat /etc/current-system-packages | wc -l)
    package_manager="nix"
fi



os="$(source /etc/os-release && echo $PRETTY_NAME)"
uptime="$(uptime -p | sed -e "s|up ||g" -e "s|,||g")"
kernel="$(uname -r)"
cpu="$(cat /proc/cpuinfo | grep "model name" | awk -F ":" '{ print $2}' | uniq)"
gpu="$(nvidia-smi -L | sed -E 's/\(.*//' | awk -F ":" '{print $2}')"

lyric="$(cat ~/Music/phoebe/cleaned/*/* | shuf -n 1)"


memused="$(free -m | awk '/Mem/ {print $3}')"
memtotal="$(free -m | awk '/Mem/ {print $2}')"
category="$(fg_t 158 203 219 ;echo $BOLD)"
eye_color="$(fg_c 236)"
if playerctl metadata > /dev/null 2>&1; then
    song=$(playerctl metadata --format "{{title}} - {{artist}}")
else
    song="${ITALIC}always listening to phoebe bridgers${NORMAL}"
fi
wm=$DESKTOP_SESSION
time=$(date "+%I:%M %p")
date=$(date "+%a %d %b %G")
uptime=$(uptime -p)

#cat << EOF
#    
#      ${W_BG}     ${NORMAL}            
#     ${W_BG}       ${NORMAL}      
#    ${W_BG}  ${eye_color} ${W_BG} ${eye_color} ${W_BG}  ${NORMAL}         ${ITALIC}$(fg_t 158 203 219)jesus christ i'm so blue all the time ${NORMAL}
#    ${W_BG}${B_FG}         ${NORMAL}         
#    ${W_BG}${B_FG}  ,  ,   ${NORMAL}         
#    ${W_BG}${B_FG}         ${NORMAL}         ${category} :${NORMAL} $os
#    ${W_BG}${B_FG} ,   , , ${NORMAL}         ${category} :${NORMAL}$cpu   
#    ${W_BG}${B_FG}         ${NORMAL}         ${category} :${NORMAL} $packages (pacman)
#    ${W_BG}${B_FG}   ,   , ${NORMAL}         ${category} :${NORMAL} $uptime 
#    ${W_BG}${B_FG} |       ${NORMAL}         ${category}ﲶ :${NORMAL} $kernel 
#    ${W_BG}${B_FG}  ,  | , ${NORMAL}         ${category} :${NORMAL} $song
#    ${W_BG}${B_FG} ,  ,    ${NORMAL}
#    ${W_BG}${B_FG}         ${NORMAL}
#    ${W_BG}${B_FG} |  |  | ${NORMAL}
#EOF

#Small
if [ "$1" = "-s" ]; then
    cat << EOF
      ${W_FG}▄▄▄▄▄${NORMAL}            
     ${W_BG}       ${NORMAL}      
    ${W_BG}  ${eye_color} ${W_BG} ${eye_color} ${W_BG}  ${NORMAL}         ${ITALIC}$(fg_t 158 203 219)$lyric${NORMAL} 
    ${W_BG}${B_FG}         ${NORMAL}         ${category}$time ${NORMAL}
    ${W_BG}${B_FG}  ,  ,   ${NORMAL}         ${category}os:${NORMAL} $os
    ${W_BG}${B_FG}         ${NORMAL}         ${category}cpu:${NORMAL}$cpu
    ${W_BG}${B_FG} ,   , , ${NORMAL}         ${category}mem:${NORMAL} ${memused}MB / ${memtotal}MB

EOF
    exit 0
fi


cat << EOF
    
      ${W_FG}▄▄▄▄▄${NORMAL}            
     ${W_BG}       ${NORMAL}      
    ${W_BG}  ${eye_color} ${W_BG} ${eye_color} ${W_BG}  ${NORMAL}         ${ITALIC}$(fg_t 158 203 219)$lyric${NORMAL}
    ${W_BG}${B_FG}         ${NORMAL}         
    ${W_BG}${B_FG}  ,  ,   ${NORMAL}         ${category}date:${NORMAL} $date
    ${W_BG}${B_FG}         ${NORMAL}         ${category}os:${NORMAL} $os
    ${W_BG}${B_FG} ,   , , ${NORMAL}         ${category}cpu:${NORMAL}$cpu   
    ${W_BG}${B_FG}         ${NORMAL}         ${category}mem:${NORMAL} ${memused}MB / ${memtotal}MB
    ${W_BG}${B_FG}   ,   , ${NORMAL}         ${category}packages:${NORMAL} $packages ($package_manager)
    ${W_BG}${B_FG} |       ${NORMAL}         ${category}gpu:${NORMAL}$gpu
    ${W_BG}${B_FG}  ,  | , ${NORMAL}         ${category}kernel:${NORMAL} $kernel 
    ${W_BG}${B_FG} ,  ,    ${NORMAL}         ${category}wm:${NORMAL} $wm
    ${W_BG}${B_FG}         ${NORMAL}         ${category}music:${NORMAL} $song 
    ${W_BG}${B_FG}         ${NORMAL}         ${category}uptime:${NORMAL} $uptime
    ${W_BG}${B_FG} |  |  | ${NORMAL}
    
EOF

#cat << EOF
#    
#      ${W_FG}▄▄▄▄▄${NORMAL}            
#     ${W_BG}       ${NORMAL}      
#    ${W_FG}▐${W_BG} ${eye_color} ${W_BG} ${eye_color} ${W_BG} ${NORMAL}${W_FG}▌${NORMAL}         ${ITALIC}$(fg_t 158 203 219)jesus christ i'm so blue all the time ${NORMAL}
#    ${W_FG}▐${W_BG}${B_FG}       ${NORMAL}${W_FG}▌${NORMAL}         
#    ${W_FG}▐${W_BG}${B_FG} ,  ,  ${NORMAL}${W_FG}▌${NORMAL}         
#    ${W_FG}▐${W_BG}${B_FG}       ${NORMAL}${W_FG}▌${NORMAL}         ${category}os:${NORMAL}  $os
#    ${W_FG}▐${W_BG}${B_FG},   , ,${NORMAL}${W_FG}▌${NORMAL}         ${category}cpu:${NORMAL} $cpu   
#    ${W_FG}▐${W_BG}${B_FG}       ${NORMAL}${W_FG}▌${NORMAL}         ${category}packages:${NORMAL} $packages (pacman)
#    ${W_FG}▐${W_BG}${B_FG}  ,   ,${NORMAL}${W_FG}▌${NORMAL}         ${category}uptime:${NORMAL} $uptime 
#    ${W_FG}▐${W_BG}${B_FG}|      ${NORMAL}${W_FG}▌${NORMAL}         ${category}kernel:${NORMAL} $kernel 
#    ${W_FG}▐${W_BG}${B_FG} ,  | ,${NORMAL}${W_FG}▌${NORMAL}         ${category}wm:${NORMAL} $wm
#    ${W_FG}▐${W_BG}${B_FG},  ,   ${NORMAL}${W_FG}▌${NORMAL}         ${category}music:${NORMAL} $song
#    ${W_FG}▐${W_BG}${B_FG}       ${NORMAL}${W_FG}▌${NORMAL}
#    ${W_FG}▐${W_BG}${B_FG}|  |  |${NORMAL}${W_FG}▌${NORMAL}
#    
#EOF




#cat << EOF
#
#    ${ITALIC}$(fg_t 158 203 219)jesus christ i'm so blue all the time ${NORMAL}
#
#                      ${W_BG}     ${NORMAL}            
#                     ${W_BG}       ${NORMAL}      
#                    ${W_BG}  ${eye_color} ${W_BG} ${eye_color} ${W_BG}  ${NORMAL}         
#                    ${W_BG}${B_FG}         ${NORMAL}         
#                    ${W_BG}${B_FG}  ,  ,   ${NORMAL}         
#                    ${W_BG}${B_FG}         ${NORMAL}         
#                    ${W_BG}${B_FG} ,   , , ${NORMAL}         
#                    ${W_BG}${B_FG}         ${NORMAL}         
#                    ${W_BG}${B_FG}   ,   , ${NORMAL}         
#                    ${W_BG}${B_FG} |       ${NORMAL}         
#                    ${W_BG}${B_FG}  ,  | , ${NORMAL}
#                    ${W_BG}${B_FG} ,  ,    ${NORMAL}
#                    ${W_BG}${B_FG}         ${NORMAL}
#                    ${W_BG}${B_FG} |  |  | ${NORMAL}
#       ${category}os${NORMAL}  
#             $os
#       ${category}cpu${NORMAL} 
#            $cpu   
#       ${category}packages${NORMAL} 
#             $packages (pacman)
#       ${category}uptime${NORMAL} 
#             $uptime 
#       ${category}kernel${NORMAL} 
#             $kernel             
#EOF









#cat << EOF
#    ${W_FG},;;;;,       
#  /${W_BG}      ${NORMAL}\\
# /${W_BG}        ${NORMAL}\\
#;${W_BG} ${B_BG}  ${W_BG} ${B_BG}  ${W_BG}    ${NORMAL}$(fg_c $WHITE);${NORMAL}
#|${W_BG}          ${NORMAL}|${NORMAL}
#|${W_BG}${B_FG}  ,   ,   ${NORMAL}|
#|${W_BG}${B_FG}          ${NORMAL}|
#|${W_BG}${B_FG} ,    , , ${NORMAL}|
#|${W_BG}${B_FG}          ${NORMAL}|
#|${W_BG}${B_FG}   , ,  , ${NORMAL}|
#|${W_BG}${B_FG}          ${NORMAL}|
#|${W_BG}${B_FG}  ,     , ${NORMAL}|
#|${W_BG}${B_FG} ,   ,    ${NORMAL}|
#|${W_BG}${B_FG}          ${NORMAL}|
#|${W_BG}${B_FG} |   |  | ${NORMAL}|
#EOF


#cat << EOF
#   ,;;;;,
#  /      \\
# /        \\
#;  ${B_FG}0   0   ${NORMAL};
#|          |
#|  ,   ,   |
#|          |
#| ,    , , |
#|          |
#|   , ,  , |
#|          |
#|  ,     , |
#| ,   ,    |
#|          |
#| |   |  | |
#EOF

