#                                _
#  __ _ _   _ ___  ___ _   _| |__   ___ _ __
# / _` | | | / __|/ __| | | | '_ \ / _ \ '__|
#| (_| | |_| \__ \ (__| |_| | |_) |  __/ |
# \__,_|\__,_|___/\___|\__, |_.__/ \___|_|
#                      |___/
#          This file is generated by the `write-flake` script. To make changes, edit the source files in `aspects/modules/` and run `nix run .#write-flake`.
{
  outputs =
    inputs:
    let
      # Flake-LEVEL input overrides. ./patched-inputs.nix returns an attrset
      # that is merged over `inputs`, so the result is what every module
      # (and flake-level import) sees as `inputs`. Patched sources are built
      # with the pinned system below; empty patched-inputs.nix is a no-op
      # (pkgs is only forced when an override actually uses it).
      imports =
        with inputs.nixpkgs.lib;
        ./aspects
        |> fileset.fileFilter (file: file.hasExt "nix" && !hasPrefix "_" file.name)
        |> fileset.toList;

      inputsFn =
        finalInputs:
        inputs.flake-parts.lib.mkFlake
          {
            inputs = finalInputs;
            specialArgs = {
              realInputs = inputs;
              lib = inputs.nixpkgs.lib;
            };
          }
          {
            # Import all *.nix files in the ./aspects directory
            # Except ones that start with '_'
            inherit imports;

            _module.args.rootPath = ./.;
          };
      output =
        let
          patchedInputs = (inputsFn inputs).newInputs;
        in
        inputsFn (patchedInputs);
    in
    builtins.removeAttrs output [ "newInputs" ];

  nixConfig = {
    extra-substituters = [
      "https://cache.ivymect.in/main"
      "https://cache.nixos.org"
      "https://devenv.cachix.org"
      "https://nix-community.cachix.org"
    ];
    extra-trusted-public-keys = [
      "main:4PgSIjmT7n9adSn4hDnnKXoERhCZR1dTlvj74k+6vT0="
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
      "devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw="
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    ];
  };

  inputs = {
    age-plugin-gpg = {
      url = "github:certainlach/age-plugin-gpg";
      inputs = {
        crane.follows = "crane";
        nixpkgs.follows = "nixpkgs";
        rust-overlay.follows = "rust-overlay";
      };
    };
    agenix = {
      url = "github:ryantm/agenix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    agenix-rekey = {
      url = "github:oddlama/agenix-rekey";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    arion.url = "github:hercules-ci/arion";
    celler = {
      url = "github:blitz/celler/main";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    crane.url = "github:ipetkov/crane";
    darwin = {
      url = "github:nix-darwin/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    den.url = "github:denful/den/latest";
    den-diagram.url = "github:denful/den-diagram";
    deploy-rs = {
      url = "github:serokell/deploy-rs";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    devshell.url = "github:numtide/devshell";
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    disko-zfs = {
      url = "github:numtide/disko-zfs";
      inputs = {
        disko.follows = "disko";
        flake-parts.follows = "flake-parts";
        nixpkgs.follows = "nixpkgs";
      };
    };
    emacs.url = "github:nix-community/emacs-overlay";
    flake-compat = {
      url = "github:nixos/flake-compat";
      flake = false;
    };
    flake-file.url = "github:denful/flake-file";
    flake-parts = {
      url = "github:hercules-ci/flake-parts";
      inputs.nixpkgs-lib.follows = "nixpkgs";
    };
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    homebrew-cask = {
      url = "github:homebrew/homebrew-cask";
      flake = false;
    };
    homebrew-core = {
      url = "github:homebrew/homebrew-core";
      flake = false;
    };
    homebrew-speedtest = {
      url = "github:teamookla/homebrew-speedtest";
      flake = false;
    };
    homebrew-typewhisper = {
      url = "github:typewhisper/homebrew-tap";
      flake = false;
    };
    impermanence.url = "github:nix-community/impermanence";
    import-tree.url = "github:vic/import-tree";
    kanata = {
      url = "github:auscyber/kanata";
      inputs = {
        crane.follows = "crane";
        nixpkgs.follows = "nixpkgs";
      };
    };
    lanzaboote = {
      url = "github:nix-community/lanzaboote/v1.1.0";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    merged-updates.url = "github:nixos/nixpkgs?ref=nixpkgs-unstable";
    my-nur = {
      url = "github:auscyber/nur-packages";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    neovim-nightly-overlay = {
      url = "github:nix-community/neovim-nightly-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nh.url = "github:nix-community/nh";
    niri = {
      url = "github:sodiboo/niri-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-flatpak.url = "github:gmodena/nix-flatpak/";
    nix-homebrew.url = "github:zhaofengli/nix-homebrew";
    nix-openclaw = {
      url = "github:openclaw/nix-openclaw";
      inputs = {
        home-manager.follows = "home-manager";
        nixpkgs.follows = "nixpkgs";
      };
    };
    nixcord.url = "github:kaylorben/nixcord";
    nixos-hardware.url = "github:NixOS/nixos-hardware";
    nixos-images = {
      url = "github:nvmd/nixos-images/sdimage-installer";
      inputs = {
        nixos-stable.follows = "nixpkgs-nvmd";
        nixos-unstable.follows = "nixpkgs-nvmd";
      };
    };
    nixos-mailserver.url = "gitlab:simple-nixos-mailserver/nixos-mailserver";
    nixos-raspberrypi.url = "github:nvmd/nixos-raspberrypi/main";
    nixos-wsl.url = "github:nix-community/NixOS-WSL/main";
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixpkgs-unstable";
    nixpkgs-nvmd.url = "github:nvmd/nixpkgs/modules-with-keys-25.11";
    nixvim.url = "github:nix-community/nixvim";
    nixvirt = {
      url = "https://flakehub.com/f/AshleyYakeley/NixVirt/*.tar.gz";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    noctalia = {
      url = "github:noctalia-dev/noctalia";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nur = {
      url = "github:nix-community/NUR";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nvfetcher.url = "github:berberman/nvfetcher";
    op-shell-plugins.url = "github:1Password/shell-plugins";
    pandoc.url = "github:srid/pandoc?ref=haskell-flake-revamp";
    rift.url = "github:auscyber/rift";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    searchix = {
      url = "git+https://git.alin.ovh/searchix?ref=refs/tags/v0.4.4";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    stylix.url = "github:nix-community/stylix";
    zen-browser = {
      url = "github:0xc000022070/zen-browser-flake";
      inputs = {
        home-manager.follows = "home-manager";
        nixpkgs.follows = "nixpkgs";
      };
    };
  };
}
