#                                _
#  __ _ _   _ ___  ___ _   _| |__   ___ _ __
# / _` | | | / __|/ __| | | | '_ \ / _ \ '__|
#| (_| | |_| \__ \ (__| |_| | |_) |  __/ |
# \__,_|\__,_|___/\___|\__, |_.__/ \___|_|
#                      |___/
#          This file is generated by the `write-flake` script. To make changes, edit the source files in `aspects/modules/` and run `nix run .#write-flake`.
{
  outputs =
    inputs:
    let
      # Flake-LEVEL input overrides. ./patched-inputs.nix returns an attrset
      # that is merged over `inputs`, so the result is what every module
      # (and flake-level import) sees as `inputs`. Patched sources are built
      # with the pinned system below; empty patched-inputs.nix is a no-op
      # (pkgs is only forced when an override actually uses it).
      imports =
        with inputs.nixpkgs.lib;
        ./aspects
        |> fileset.fileFilter (file: file.hasExt "nix" && !hasPrefix "_" file.name)
        |> fileset.toList;

      inputsFn =
        finalInputs:
        inputs.flake-parts.lib.mkFlake
          {
            inputs = finalInputs;
            specialArgs = {
              realInputs = inputs;
              lib = inputs.nixpkgs.lib;
            };
          }
          {
            # Import all *.nix files in the ./aspects directory
            # Except ones that start with '_'
            inherit imports;

            _module.args.rootPath = ./.;
          };
      output =
        let
          patchedInputs = (inputsFn inputs).newInputs;
        in
        inputsFn (patchedInputs);
    in
    builtins.removeAttrs output [ "newInputs" ];

  nixConfig = {
    extra-substituters = [
      "https://cache.nixos.org"
      "https://devenv.cachix.org"
      "https://nix-community.cachix.org"
    ];
    extra-trusted-public-keys = [
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
      "devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw="
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    ];
  };

  inputs = {
    age-plugin-gpg = {
      url = "github:certainlach/age-plugin-gpg";
      inputs = {
        crane.follows = "crane";
        flake-parts.follows = "flake-parts";
        nixpkgs.follows = "nixpkgs";
        rust-overlay.follows = "rust-overlay";
      };
    };
    agenix = {
      url = "github:ryantm/agenix";
      inputs = {
        darwin.follows = "darwin";
        home-manager.follows = "home-manager";
        nixpkgs.follows = "nixpkgs";
      };
    };
    agenix-rekey = {
      url = "github:oddlama/agenix-rekey";
      inputs = {
        devshell.follows = "devshell";
        flake-parts.follows = "flake-parts";
        nixpkgs.follows = "nixpkgs";
      };
    };
    arion = {
      url = "github:hercules-ci/arion";
      inputs = {
        flake-parts.follows = "flake-parts";
        nixpkgs.follows = "nixpkgs";
      };
    };
    celler = {
      url = "github:blitz/celler/main";
      inputs = {
        crane.follows = "crane";
        flake-parts.follows = "flake-parts";
        nixpkgs.follows = "nixpkgs";
      };
    };
    crane = {
      url = "github:ipetkov/crane";
      inputs = { };
    };
    darwin = {
      url = "github:nix-darwin/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    den = {
      url = "github:denful/den/latest";
      inputs = { };
    };
    den-diagram = {
      url = "github:denful/den-diagram";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    devshell = {
      url = "github:numtide/devshell";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    emacs = {
      url = "github:nix-community/emacs-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    flake-compat = {
      url = "github:nixos/flake-compat";
      flake = false;
    };
    flake-file = {
      url = "github:denful/flake-file";
      inputs = { };
    };
    flake-parts = {
      url = "github:hercules-ci/flake-parts";
      inputs.nixpkgs-lib.follows = "nixpkgs";
    };
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    homebrew-cask = {
      url = "github:homebrew/homebrew-cask";
      flake = false;
    };
    homebrew-core = {
      url = "github:homebrew/homebrew-core";
      flake = false;
    };
    homebrew-speedtest = {
      url = "github:teamookla/homebrew-speedtest";
      flake = false;
    };
    homebrew-typewhisper = {
      url = "github:typewhisper/homebrew-tap";
      flake = false;
    };
    impermanence = {
      url = "github:nix-community/impermanence";
      inputs = {
        home-manager.follows = "home-manager";
        nixpkgs.follows = "nixpkgs";
      };
    };
    import-tree = {
      url = "github:vic/import-tree";
      inputs = { };
    };
    my-nur = {
      url = "github:auscyber/nur-packages";
      inputs = {
        nixpkgs.follows = "nixpkgs";
        nvfetcher.follows = "nvfetcher";
      };
    };
    nh = {
      url = "github:nix-community/nh";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    niri = {
      url = "github:sodiboo/niri-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-flatpak = {
      url = "github:gmodena/nix-flatpak/";
      inputs = { };
    };
    nix-homebrew = {
      url = "github:zhaofengli/nix-homebrew";
      inputs = { };
    };
    nix-openclaw = {
      url = "github:openclaw/nix-openclaw";
      inputs = {
        home-manager.follows = "home-manager";
        nixpkgs.follows = "nixpkgs";
      };
    };
    nixcord = {
      url = "github:kaylorben/nixcord";
      inputs = {
        flake-parts.follows = "flake-parts";
        nixpkgs.follows = "nixpkgs";
      };
    };
    nixos-hardware = {
      url = "github:NixOS/nixos-hardware";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nixos-images = {
      url = "github:nvmd/nixos-images/sdimage-installer";
      inputs = {
        nixos-stable.follows = "nixpkgs-nvmd";
        nixos-unstable.follows = "nixpkgs-nvmd";
      };
    };
    nixos-mailserver = {
      url = "gitlab:simple-nixos-mailserver/nixos-mailserver";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nixos-raspberrypi = {
      url = "github:nvmd/nixos-raspberrypi/main";
      inputs = {
        nixos-images.follows = "nixos-images";
        nixpkgs.follows = "nixpkgs";
      };
    };
    nixos-wsl = {
      url = "github:nix-community/NixOS-WSL/main";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nixpkgs = {
      url = "github:nixos/nixpkgs?ref=nixpkgs-unstable";
      inputs = { };
    };
    nixpkgs-nvmd = {
      url = "github:nvmd/nixpkgs/modules-with-keys-25.11";
      inputs = { };
    };
    nixvim = {
      url = "github:nix-community/nixvim";
      inputs = {
        flake-parts.follows = "flake-parts";
        nixpkgs.follows = "nixpkgs";
      };
    };
    nur = {
      url = "github:nix-community/NUR";
      inputs = {
        flake-parts.follows = "flake-parts";
        nixpkgs.follows = "nixpkgs";
      };
    };
    nvfetcher = {
      url = "github:berberman/nvfetcher";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    op-shell-plugins = {
      url = "github:1Password/shell-plugins";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    rift = {
      url = "github:auscyber/rift";
      inputs = {
        crane.follows = "crane";
        flake-parts.follows = "flake-parts";
        nixpkgs.follows = "nixpkgs";
      };
    };
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    stylix = {
      url = "github:nix-community/stylix";
      inputs = {
        flake-parts.follows = "flake-parts";
        nixpkgs.follows = "nixpkgs";
        nur.follows = "nur";
      };
    };
    zen-browser = {
      url = "github:0xc000022070/zen-browser-flake";
      inputs = {
        home-manager.follows = "home-manager";
        nixpkgs.follows = "nixpkgs";
      };
    };
  };
}
