#                                _
#  __ _ _   _ ___  ___ _   _| |__   ___ _ __
# / _` | | | / __|/ __| | | | '_ \ / _ \ '__|
#| (_| | |_| \__ \ (__| |_| | |_) |  __/ |
# \__,_|\__,_|___/\___|\__, |_.__/ \___|_|
#                      |___/
#          This file is generated by the `write-flake` script. To make changes, edit the source files in `aspects/modules/` and run `nix run .#write-flake`.
{
  outputs =
    inputs:
    inputs.flake-parts.lib.mkFlake { inherit inputs; } {
      # Import all *.nix files in the ./aspects directory
      # Except ones that start with '_'
      imports =
        with inputs.nixpkgs.lib;
        ./aspects
        |> fileset.fileFilter (file: file.hasExt "nix" && !hasPrefix "_" file.name)
        |> fileset.toList;

      _module.args.rootPath = ./.;
    };

  nixConfig = {
    experimental-features = [
      "nix-command"
      "flakes"
      "pipe-operators"
    ];
    extra-substituters = [
      "https://cache.ivymect.in/main"
      "https://cache.ivymect.in/main"
      "https://cache.nixos.org"
      "https://devenv.cachix.org"
      "https://nix-community.cachix.org"
    ];
    extra-trusted-public-keys = [
      "main:4PgSIjmT7n9adSn4hDnnKXoERhCZR1dTlvj74k+6vT0="
      "main:4PgSIjmT7n9adSn4hDnnKXoERhCZR1dTlvj74k+6vT0="
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
      "devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw="
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    ];
  };

  inputs = {
    age-plugin-gpg = {
      type = "git";
      url = "./.";
      ref = "inputs/age-plugin-gpg";
      inputs = {
        nixpkgs.follows = "nixpkgs";
        rust-overlay.follows = "rust-overlay";
      };
    };
    agenix = {
      url = "github:auscyber/agenix?ref=add-templates";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    agenix-rekey.url = "github:auscyber/agenix-rekey?ref=add-template-support";
    allfollow.url = "github:spikespaz/allfollow";
    celler = {
      url = "github:blitz/celler/main";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    darwin.url = "github:auscyber/nix-darwin?ref=inputs/darwin";
    den.url = "github:denful/den";
    den-diagram.url = "github:denful/den-diagram";
    flake-file.url = "github:denful/flake-file";
    flake-parts = {
      url = "github:hercules-ci/flake-parts";
      inputs.nixpkgs-lib.follows = "nixpkgs";
    };
    home-manager = {
      url = "github:auscyber/home-manager?ref=inputs/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    homebrew-cask = {
      url = "github:homebrew/homebrew-cask";
      flake = false;
    };
    homebrew-core = {
      url = "github:homebrew/homebrew-core";
      flake = false;
    };
    homebrew-speedtest = {
      url = "github:teamookla/homebrew-speedtest";
      flake = false;
    };
    homebrew-typewhisper = {
      url = "github:typewhisper/homebrew-tap";
      flake = false;
    };
    import-tree.url = "github:vic/import-tree";
    nh.url = "github:auscyber/nh?ref=inputs/nh";
    nix-homebrew.url = "github:zhaofengli/nix-homebrew";
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixpkgs-unstable";
    nixvim = {
      url = "github:nix-community/nixvim";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nur = {
      url = "github:nix-community/NUR";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    op-shell-plugins.url = "github:1Password/shell-plugins";
    rift.url = "github:auscyber/rift";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    stylix.url = "github:nix-community/stylix";
    zen-browser = {
      url = "github:0xc000022070/zen-browser-flake";
      inputs = {
        home-manager.follows = "home-manager";
        nixpkgs.follows = "nixpkgs";
      };
    };
  };
}
