# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  alx-wol = {
    pname = "alx-wol";
    version = "alx-wol-3.1";
    src = fetchFromGitHub {
      owner = "AndiWeiss";
      repo = "alx-wol";
      rev = "alx-wol-3.1";
      fetchSubmodules = false;
      sha256 = "sha256-Sfq1vnf+UXNtSSBjGPe0Ignu6G8clp4RrVpeT8F5Xw8=";
    };
  };
  app_font = {
    pname = "app_font";
    version = "d52c78b73970e6343026b12092a030fb73e4bd30";
    src = fetchgit {
      url = "https://github.com/kvndrsslr/sketchybar-app-font";
      rev = "d52c78b73970e6343026b12092a030fb73e4bd30";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pnAFT3MaPpAHObBkrGk9pSOGZdykjTHcRLBq4hCtVf0=";
    };
    date = "2026-07-20";
  };
  cotabby = {
    pname = "cotabby";
    version = "v0.6.2-beta";
    src = fetchurl {
      url = "https://github.com/fujacob/cotabby/releases/download/v0.6.2-beta/Cotabby.dmg";
      sha256 = "sha256-2sOqH2iI7gw5J8QnvG5PAsb4F4m1DW2uPSQHLIK81Pk=";
    };
  };
  eagle-nvim = {
    pname = "eagle-nvim";
    version = "d503b168932160b07d4d09551d90d5fbb388b641";
    src = fetchFromGitHub {
      owner = "soulis-1256";
      repo = "eagle.nvim";
      rev = "d503b168932160b07d4d09551d90d5fbb388b641";
      fetchSubmodules = false;
      sha256 = "sha256-Gug086B7EQ8qX6vKChnbjC5R2GroeqPuj3RWcbYOI9A=";
    };
    date = "2026-02-10";
  };
  helium_linux = {
    pname = "helium_linux";
    version = "0.14.7.1";
    src = fetchTarball {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.14.7.1/helium-0.14.7.1-x86_64_linux.tar.xz";
      sha256 = "sha256-fJDwfUJChM9Fl7mckDKI7oIe5rG7+P11AdEkd+MlN3o=";
    };
  };
  helium_macos = {
    pname = "helium_macos";
    version = "0.14.7.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-macos/releases/download/0.14.7.1/helium_0.14.7.1_arm64-macos.dmg";
      sha256 = "sha256-ZwIhBInDTRRDkp1xuZtoBIZMJ1ir0CKX1O2H1E15TxY=";
    };
  };
  jankyborders = {
    pname = "jankyborders";
    version = "a7297ca7d1933f3a30b12e8f10750e8d84eeee1e";
    src = fetchgit {
      url = "https://github.com/felixkratz/jankyborders";
      rev = "a7297ca7d1933f3a30b12e8f10750e8d84eeee1e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-j4hdW7JXTmSrE4bwlOkUYxA32AD011za7dmItwwIvyg=";
    };
    date = "2026-05-14";
  };
  kanata-tray = {
    pname = "kanata-tray";
    version = "v0.8.0";
    src = fetchFromGitHub {
      owner = "rszyma";
      repo = "kanata-tray";
      rev = "v0.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-RTLFDB/irtEhEHwarROGmS4jNdRhruU1JKen48ADzZg=";
    };
  };
  lix = {
    pname = "lix";
    version = "eb7009316b012d48a82735e36bc9485a32558658";
    src = fetchgit {
      url = "https://git.lix.systems/lix-project/lix.git";
      rev = "eb7009316b012d48a82735e36bc9485a32558658";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-7qgPwwlb0d5OnO4GWS6iOSc6zXwAq7I8IlYgi+uytdo=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-7qgPwwlb0d5OnO4GWS6iOSc6zXwAq7I8IlYgi+uytdo=/Cargo.lock";
      outputHashes = {
        "zngur-0.10.0" = "sha256-q8mkHbZwrgLF61Esbd9nK9y8GnZqHWzSubY9ERibBEo=";
      };
    };
    date = "2026-07-21";
  };
  lspmux = {
    pname = "lspmux";
    version = "18861f9d59e74ece8d867772cf07fa302c2dae98";
    src = fetchgit {
      url = "https://codeberg.org/p2502/lspmux.git";
      rev = "18861f9d59e74ece8d867772cf07fa302c2dae98";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-OchqUe8GdBPL6tE3zpdaThfhzYZhYluagz1yXiexFT0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-OchqUe8GdBPL6tE3zpdaThfhzYZhYluagz1yXiexFT0=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-03-11";
  };
  pam_rssh = {
    pname = "pam_rssh";
    version = "v1.2.1";
    src = fetchFromGitHub {
      owner = "z4yx";
      repo = "pam_rssh";
      rev = "v1.2.1";
      fetchSubmodules = true;
      sha256 = "sha256-yHB6tEQuUFYve6GgAW6VuLSw49q0l0VzgH1vIquPNMQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-yHB6tEQuUFYve6GgAW6VuLSw49q0l0VzgH1vIquPNMQ=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  proton-ge-bin = {
    pname = "proton-ge-bin";
    version = "GE-Proton11-1";
    src = fetchTarball {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton11-1/GE-Proton11-1.tar.gz";
      sha256 = "sha256-I7SSvzQQ/NqdvwjpJ9IFFtAaTS+rgHUyXx0us1vIOnw=";
    };
  };
  sketchybar = {
    pname = "sketchybar";
    version = "6284ee816601486ace33ca48a0271832eec6de35";
    src = fetchFromGitHub {
      owner = "felixkratz";
      repo = "sketchybar";
      rev = "6284ee816601486ace33ca48a0271832eec6de35";
      fetchSubmodules = false;
      sha256 = "sha256-5tyc/yYzdV/3JTtujuj7le/14XkC7TlN/nZg7tOZsNg=";
    };
    date = "2026-06-04";
  };
  vscode-kanata = {
    pname = "vscode-kanata";
    version = "701dbf9a10a6857fe9ea72944c84475ab58c81c8";
    src = fetchgit {
      url = "https://github.com/rszyma/vscode-kanata.git";
      rev = "701dbf9a10a6857fe9ea72944c84475ab58c81c8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-w0hFYVAlqq9wl1xNEC/oHG32BeklP8t+++3EaU8Ximg=";
    };
    date = "2026-07-15";
  };
  zotero-actions-tags = {
    pname = "zotero-actions-tags";
    version = "2.5.2";
    src = fetchurl {
      url = "https://github.com/windingwind/zotero-actions-tags/releases/download/v2.5.2/actions-and-tags-for-zotero.xpi";
      sha256 = "sha256-ASPnaCjkRuyLHIg1gsPQ+hFMxFnl7gNxclSfAOPCxek=";
    };
  };
  zotero-aria = {
    pname = "zotero-aria";
    version = "v0.7.5";
    src = fetchurl {
      url = "https://github.com/lifan0127/ai-research-assistant/releases/download/v0.7.5/aria.xpi";
      sha256 = "sha256-xqki7703PPYdHqUwDGyG3+nBfabYVfnGz10EJ2oeH7c=";
    };
  };
  zotero-attanger = {
    pname = "zotero-attanger";
    version = "1.4.8";
    src = fetchurl {
      url = "https://github.com/MuiseDestiny/zotero-attanger/releases/download/1.4.8/zotero-attanger.xpi";
      sha256 = "sha256-4ybf5lABuWzWVfViQFyH4JX2Yoh0lv0toqDvzLFMuWc=";
    };
  };
  zotero-better-bibtex = {
    pname = "zotero-better-bibtex";
    version = "9.0.47";
    src = fetchurl {
      url = "https://github.com/retorquere/zotero-better-bibtex/releases/download/v9.0.47/zotero-better-bibtex-9.0.47.xpi";
      sha256 = "sha256-yI7l5ryUoJc7RtyNEo8L7ikV8sShkWSPKsl3lzJ04AQ=";
    };
  };
  zotero-notero = {
    pname = "zotero-notero";
    version = "556359043a4b61df5802b6650cbdbec6450bf9d4";
    src = fetchFromGitHub {
      owner = "dvanoni";
      repo = "notero";
      rev = "556359043a4b61df5802b6650cbdbec6450bf9d4";
      fetchSubmodules = false;
      sha256 = "sha256-hl93l5W1qvW+XXSphvw8/36+xhfbajjIPNPqikWj/+k=";
    };
    date = "2026-05-08";
  };
  zotero-ocr = {
    pname = "zotero-ocr";
    version = "0.9.5.1";
    src = fetchurl {
      url = "https://github.com/UB-Mannheim/zotero-ocr/releases/download/0.9.5.1/zotero-ocr-0.9.5.1.xpi";
      sha256 = "sha256-8QCz5gy087tpFmV261fnb3ACsk/1JkjCpoJ9aLU1r44=";
    };
  };
  zotero-papersgpt = {
    pname = "zotero-papersgpt";
    version = "papersgpt-v0.6.1";
    src = fetchurl {
      url = "https://github.com/papersgpt/papersgpt-for-zotero/releases/download/papersgpt-v0.6.1/papersgpt-v0.6.1.xpi";
      sha256 = "sha256-bOHWVQD+ArzpTLt2MKyRAAs9yV/P1SX2AXqaAmmULoM=";
    };
  };
  zotero-zotlit = {
    pname = "zotero-zotlit";
    version = "2.0.0-alpha.3";
    src = fetchurl {
      url = "https://github.com/aidenlx/zotlit/releases/download/zt-2.0.0-alpha.3/zotlit-zotero-2.0.0-alpha.3.xpi";
      sha256 = "sha256-MHbi4AB+9Ouas19d+YhAef3zEeRWsSsVGtmW024DOwY=";
    };
  };
}
