# DO-NOT-EDIT: Generated by github:vic/flake-file.
# To re-generate use: nix-shell . -A flake-file.sh --run write-inputs
{
  darwin.url = "github:nix-darwin/nix-darwin";
  den.url = "github:denful/den";
  flake-file.url = "github:denful/flake-file";
  flake-parts.url = "github:hercules-ci/flake-parts";
  home-manager = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:nix-community/home-manager";
  };
  homebrew-cask = {
    flake = false;
    url = "github:homebrew/homebrew-cask";
  };
  homebrew-core = {
    flake = false;
    url = "github:homebrew/homebrew-core";
  };
  homebrew-speedtest = {
    flake = false;
    url = "github:teamookla/homebrew-speedtest";
  };
  homebrew-typewhisper = {
    flake = false;
    url = "github:typewhisper/homebrew-tap";
  };
  nix-auto-follow = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:fzakaria/nix-auto-follow";
  };
  nix-homebrew.url = "github:zhaofengli/nix-homebrew";
  nixpkgs.url = "github:nixos/nixpkgs?ref=nixpkgs-unstable";
  nixvim.url = "github:nix-community/nixvim";
}
