# GENERATED by `nix run .#write-partition-map` -- reconcile by hand if the base
# evaluation breaks (see aspects/framework/partition-map.nix for why the derived
# classification is a starting point, not a guarantee).
#
# Which aspects live in a flake-parts partition instead of the base evaluation.
# An aspect listed here is NOT imported by the root flake, so its `ff.*` input
# declarations never reach the root `flake.nix`/`flake.lock`; they are written to
# `partitions/<bucket>/flake.nix` instead. See aspects/framework/partitions.nix.
#
# Entries are paths relative to ./aspects. A directory entry claims everything
# under it. `stubs` are the aspect names bucketed files define, stubbed inert at
# base so a base file naming a moved aspect still resolves.
{
  buckets = {
    darwin = [
      "apps/cotabby.nix"
      "base/file-local.nix"
      "darwin/base.nix"
      "darwin/finder.nix"
      "darwin/general.nix"
      "darwin/hmApps.nix"
      "darwin/homebrew.nix"
      "darwin/pam-touchid.nix"
      "desktop/sketchybar/sketchybar.nix"
      "dev/idris.nix"
      "dev/mcp-servers.nix"
      "dev/opencode.nix"
      "hosts/laptop.nix"
      "hosts/macmini.nix"
      "input/karabiner-driver.nix"
      "programs/browsers/helium.nix"
      "programs/browsers/zen.nix"
      "programs/zotero.nix"
      "services/llama-cpp.nix"
      "tooling/sudoagents.nix"
      "wms/rift/default.nix"
    ];
    dev = [
      "docs/default.nix"
      "framework/partition-map.nix"
      "tooling/ci-matrix.nix"
      "tooling/deploy.nix"
    ];
    nixos = [
      "base/local.nix"
      "desktop/bootlogo.nix"
      "desktop/plasma.nix"
      "hosts/auspc.nix"
      "hosts/contabo.nix"
      "hosts/imflopet.nix"
      "hosts/lora-pi.nix"
      "hosts/pentestvm.nix"
      "hosts/secondpc/default.nix"
      "hosts/secondpc/web.nix"
      "hosts/surfacelaptop.nix"
      "hosts/wsl-nixos.nix"
      "network/vpn-server.nix"
      "nixos/builders.nix"
      "nixos/general.nix"
      "nixos/kernels/cachyos.nix"
      "nixos/kernels/trim.nix"
      "nixos/raspberrypi.nix"
      "security/openssh.nix"
      "security/secure-boot.nix"
      "security/user-pwd.nix"
      "services/nginx.nix"
      "services/searchix.nix"
      "storage.nix"
    ];
  };

  stubs = [
    "Ivys-MacBook-Pro"
    "admin"
    "auscyber"
    "auspc"
    "bootlogo"
    "browsers/helium"
    "browsers/zen"
    "builder-server"
    "builders"
    "cachyos-kernel"
    "contabo"
    "cotabby"
    "darwin-base"
    "darwin-finder"
    "darwin-general"
    "darwin-hmApps"
    "disko"
    "file-local"
    "homebrew"
    "idris"
    "imflopet"
    "ivy"
    "ivypierlot"
    "karabiner-driver"
    "kernel-trim"
    "laptop-brew"
    "llama-cpp"
    "local"
    "lora-pi"
    "macmini"
    "mcp-servers"
    "nginx"
    "nixos"
    "nixos-general"
    "nixos-raspberrypi"
    "opencode"
    "openssh"
    "pam-touchid"
    "pentestvm"
    "plasma"
    "rift"
    "searchix"
    "secondpc"
    "secondpc-web"
    "secure-boot"
    "sketchybar"
    "sudoagents"
    "surfacelaptop"
    "user-pwd"
    "vpn-server"
    "wsl-nixos"
    "zotero"
  ];
}

