# GENERATED by `nix run .#write-patched-inputs` — do not edit by hand.
#
# The patch configuration that flake.nix needs BEFORE it can evaluate the
# flake-parts module system. Everything else about a patched input is derived
# purely at eval time: `src` from the flake input, `hash` from
# ./patches/hashes.json, and the auto-unified set (inputs that transitively
# depend on a patched one) from ./flake.lock.
#
# Only `patches` is recorded, because that is the only field any aspect
# overrides — note `nh`, which deliberately applies just edit.patch even
# though ./patches/nh/ also contains nh.patch, and `zen-browser`, which has no
# patches directory at all.
#
# `checks.patched-inputs-generated-current` fails if this drifts from the
# aspects' own declarations, so a stale file is caught by `nix flake check`
# rather than silently applying the wrong patches.
{
  age-plugin-gpg.patches = [ ./patches/age-plugin-gpg/age-plugin-gpg.patch ];

  agenix.patches = [
    ./patches/agenix/templates.patch
    ./patches/agenix/edit.patch
  ];

  agenix-rekey.patches = [
    ./patches/agenix-rekey/template.patch
    ./patches/agenix-rekey/stat-portable.patch
  ];

  darwin.patches = [
    ./patches/darwin/karabiner.patch
    ./patches/darwin/specialisation.patch
  ];

  home-manager.patches = [
    ./patches/home-manager/edit.patch
    ./patches/home-manager/one.patch
  ];

  nh.patches = [ ./patches/nh/edit.patch ];

  nix-openclaw.patches = [ ./patches/nix-openclaw/openclaw-app-resigned-hash.patch ];

  zen-browser.patches = [ ];
}
