# GENERATED by `nix run .#write-patched-inputs` — do not edit by hand.
#
# The patch configuration flake.nix needs BEFORE it can evaluate the
# flake-parts module system: which inputs are patched, with which patches,
# and the SRI hash of each resulting tree. Because the hash lives here,
# flake.nix needs no second file to build the patched inputs.
#
# Everything else is still derived purely at eval time: `src` from the
# flake input, and the auto-unified set (inputs that transitively depend
# on a patched one) from ./flake.lock.
#
# `hash = null` means no recorded hash — that tree is built locally and
# is not substitutable. `PATCH_HASHES=ignore` overrides every hash here,
# which is the way out if one goes stale: a stale hash fails the
# fixed-output build, which would otherwise take down the very evaluation
# that runs the app to regenerate it.
#
# Regenerate with `nix run .#write-patched-inputs` after changing a patch
# or bumping a patched input. `checks.patched-inputs-generated-current`
# fails if the patch lists here drift from the aspects' declarations.
{

  age-plugin-gpg.patches = [
    ./patches/age-plugin-gpg/age-plugin-gpg.patch
  ];
  agenix.patches = [
    ./patches/agenix/templates.patch
    ./patches/agenix/edit.patch
  ];
  agenix-rekey.patches = [
    ./patches/agenix-rekey/template.patch
    ./patches/agenix-rekey/stat-portable.patch
    ./patches/agenix-rekey/rekey-mkdir-p.patch
  ];
  darwin.patches = [
    ./patches/darwin/karabiner.patch
    ./patches/darwin/specialisation.patch
  ];
  home-manager.patches = [
    ./patches/home-manager/edit.patch
  ];
  nh.patches = [
    ./patches/nh/edit.patch
  ];
  zen-browser.patches = [ ];

  age-plugin-gpg.hash = "sha256-Gjjt9MiTMJS4UTcUaN514wKHrstebVsoK8sxdPRjqAU=";
  agenix.hash = "sha256-u+D8OB1XMOAIyd6/u+IKtRToTftdXc0L/A58dRCS/8M=";
  agenix-rekey.hash = "sha256-wP42oef9cVSdnGxD7VlDblRAZWtAHPiZ2pwXk7e6PCo=";
  darwin.hash = "sha256-JvpHtXBeAyTejgOMRLvUsgJy1hGu/RMt/7PI5PnBYK0=";
  home-manager.hash = "sha256-8EQ/0H5Lp+LA4L6Mj6lLfY0CsU3Ht4kZAHjAxUOmdu0=";
  nh.hash = "sha256-AB5LGXgRBAJR2cFrXDT2Gos0YGHxt97JytkSZ4uNiDE=";
  zen-browser.hash = null;
}
