# GENERATED by `nix run .#write-flake` — do not edit by hand.
#
# Everything flake.nix needs BEFORE it can evaluate the flake-parts module
# system, in one file:
#
#   `layers`  where each input is locked. RECORDED FOR INSPECTION ONLY --
#             placement is evaluated (`flake.layerPlan`, from the `layers`
#             tags on aspects), and nothing reads this back. It is here so
#             the split is readable without running an evaluation.
#
#   `inputs`  which inputs are patched, with which patches, and the SRI hash
#             of each resulting tree. This half IS read by flake.nix, which
#             is why it has to be a file: the module system cannot run until
#             the patched inputs exist.
#
# Written by `write-flake` rather than a separate command, so the hashes
# cannot drift from the layers and locks they belong to -- which is how
# `arion` ended up with patches and no hash, silently unsubstitutable.
#
# `hash = null` means no recorded hash — that tree is built locally and
# is not substitutable. `PATCH_HASHES=ignore` overrides every hash here,
# which is the way out if one goes stale: a stale hash fails the
# fixed-output build, which would otherwise take down the very evaluation
# that runs the app to regenerate it.
#
# `checks.patched-inputs-generated-current` fails if the patch lists here
# drift from the aspects' declarations.
{
  layers = {
    darwin-dev = [
      "idris2Packages"
      "pnpm-nix-provider"
    ];
    darwin-gui = [
      "coolabah"
      "paneru"
      "zen-browser"
    ];
    dev = [
      "claude-code"
      "neovim-nightly-overlay"
      "nixvim"
      "op-shell-plugins"
    ];
    gui = [
      "my-nur"
      "nur"
      "stylix"
    ];
    gui-nixos = [ "plasma-manager" ];
    homebrew = [
      "homebrew-cask"
      "homebrew-core"
      "homebrew-gcenx"
      "homebrew-speedtest"
      "homebrew-typewhisper"
      "nix-homebrew"
    ];
    nixos = [
      "arion"
      "disko"
      "disko-zfs"
      "impermanence"
      "lanzaboote"
      "nix-cachyos-kernel"
      "nix-flatpak"
      "nixos-hardware"
      "nixos-images"
      "nixos-mailserver"
      "nixos-raspberrypi"
      "nixos-wsl"
      "nixpkgs-nvmd"
      "searchix"
    ];
    root = [
      "age-plugin-gpg"
      "agenix"
      "agenix-rekey"
      "celler"
      "crane"
      "darwin"
      "ivixlib"
      "ivylix"
      "izlix"
      "nix-index-database"
    ];
  };

  inputs = {
    age-plugin-gpg.patches = [
      ./patches/age-plugin-gpg/age-plugin-gpg.patch
    ];
    agenix.patches = [
      ./patches/agenix/templates.patch
      ./patches/agenix/edit.patch
    ];
    agenix-rekey.patches = [
      ./patches/agenix-rekey/template.patch
      ./patches/agenix-rekey/stat-portable.patch
      ./patches/agenix-rekey/rekey-mkdir-p.patch
    ];
    arion.patches = [
      ./patches/arion/journald-console.patch
    ];
    darwin.patches = [
      ./patches/darwin/karabiner.patch
      ./patches/darwin/specialisation.patch
    ];
    home-manager.patches = [
      ./patches/home-manager/edit.patch
    ];
    nh.patches = [
      ./patches/nh/edit.patch
    ];
    pnpm-nix-provider.patches = [
      ./patches/pnpm-nix-provider/execute-bit.patch
    ];
    zen-browser.patches = [ ];

    age-plugin-gpg.hash = "sha256-Gjjt9MiTMJS4UTcUaN514wKHrstebVsoK8sxdPRjqAU=";
    agenix.hash = "sha256-u+D8OB1XMOAIyd6/u+IKtRToTftdXc0L/A58dRCS/8M=";
    agenix-rekey.hash = "sha256-wP42oef9cVSdnGxD7VlDblRAZWtAHPiZ2pwXk7e6PCo=";
    arion.hash = "sha256-XM8sEWDiEAwjWL1onvSuxrkgyHxL0SAwsD6dXx992NM=";
    darwin.hash = "sha256-ijSJAEM3e1gFv9vAlogYS+5ONYjOicZ7zlmo9XWesAY=";
    home-manager.hash = "sha256-aWy+wfpH3jYd8FaTtnLOGpUoSGIeypMSXkUiELZuzhc=";
    nh.hash = "sha256-sU0B7F6Vz6eaeTCtitPrE/h4K5Qldfaw0POoA9CtS1c=";
    pnpm-nix-provider.hash = "sha256-/dooptthzfGp/Qmdg27ME4frEuxH0zWxad7zceNsMzw=";
    zen-browser.hash = null;
  };
}
