tailscale:
    auth_key: ENC[AES256_GCM,data:K4pXKUpskhCmJjkMKFNjrl8Sm5hVaczFe0XxHSQQ3GUCJ8KnMnuFj6fcAB0BnY7Xxg7fy8O1yiEDPS0cFFM=,iv:fm2hx0YIWVcUhB5fQ9VJgseo4MVMH4i3DYu2XgzaL3M=,tag:cJm9C2oMnb/szH6Ii4VgHg==,type:str]
hass_token: ENC[AES256_GCM,data:uFpViZ3opnXOJup/rjpzY/fwuXvljc88CMbPaRoOIdHhKfXj5g//A18NVLpc4OOBdFaOPQekAk4mLm4a4JeUqy/avsNn49/0cjAGi7TN/61pHX6QE3/7/t2qNFeJ76vvrO0w1e4NubrtLirxXmpRM049gFd5oh954Enjm6V+dU0iu2ZaR8dZ9FZPj/SszUI/NOeU+l1veXqgCHVfXCaRPiGs3Rs/QEEVB88p2v2vkt4sOTxxGgcU,iv:kR2f0hlozhusuF4amWnMHlflunseNA9Fjgj3sha7v0c=,tag:6JMBQKQbDZr2jbu7g8XArg==,type:str]
sops:
    age:
        - recipient: age1wl25zsmys6cdzacrx4xh2fe89jk8enx4dalc52075kg9rdnuxf9qe2yw7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUXVja2ZVNmFUeUpWY1Er
            aFB2MEtpMTR5Zk00NXlSeGp0NnpxMld3d1I4ClAyUDNsTlg2ZjZRcS9wZzFjN0ZV
            NElLcDhnV1I0cnVtcVBZajNXM3NiREkKLS0tIHp1Smp1RmdkLytmSnVCNVdqT2o5
            cHdtNXJpYmVpNEJsV3hRR0lSM0tCckUK8b3ZQ+SIYP8H/KXp/5+M8MJzvAXqQWi4
            xAmxW/qQXxcJr5wmv3jGv2ZZiv8+DdzIg0yN+EhqXiOppxgzNiV7Ng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n6ufle4xhy0fe6nkwp7yzfv7mxqdm06wtp2uj0dwzrtfv4rtzpfsmslgjn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaEpDbkl1ekRZMlQ0YUYw
            SUY5WGpSZHViS25YWkZGcGxvK2ZxK2dkUVdzCmlkMjcwM2NiaVh5Tnk0OVpxV3VB
            T25jRVFVY3Fqb2JJejVOTEhDV3p4ZGMKLS0tIHNXODhPOWdXd05FbTVBcmNJaVh4
            cnNrdUNQZUpOa0dxNDA0U3dvVFpFdEUKP4Q/kWZo0GL1dM+CBzIFOQ8V5s4ppFEk
            rL6z6dYQkSRviI6tlbLRUnhNfKTx4nO190cmN45lQcHPeCPEA6GX9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T13:40:11Z"
    mac: ENC[AES256_GCM,data:UVCF+8HntWOfzGZpRDktah1EyoTeFs4SnIBI75czJ8KHDScIgea7NfTFUnQK6NCJgrn91/GwgbsGtMbIwImqXtmEEJ9llbBABo1PUP04veKCjGv1swLVxI4/3Kac3pA+HQbU9C5c9DTySPClxYHDatvczy4baIYhi7QwAVKu/1M=,iv:bihSapOk2LdA+4Hi9imqlFfVddxLm8WBx0XEwub9z7M=,tag:nSDYlHEP96XHrL5pOFLqeA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
