{
  inputs,
  lib,
  den,
  config,
  ...
}:
{
  systems = [
    "x86_64-linux"
    "aarch64-darwin"
  ];
  imports = [
    inputs.flake-file.flakeModules.default
    (lib.mkAliasOptionModule [ "ff" ] [ "flake-file" "inputs" ])
  ];
  den = {
    classes.inputs = { };
    schema.flake-mod = { };
    policies.inputs-to-flake-parts = _: [
      (den.lib.policy.route {
        fromClass = "flake-file";
        intoClass = "flake-mod";
        collectSubtree = true;
        path = [
          "flake-file"
        ];
        adaptArgs = lib.id;
        #      adaptArgs = { config, ... }: config.allModuleArgs;
      })
    ];
    policies.sources-to-flake-parts = _: [
      (den.lib.policy.route {
        fromClass = "nvfetcher";
        intoClass = "flake-mod";
        collectSubtree = true;
        path = [
        ];
        adaptArgs = lib.id;
      })
    ];
    policies.flake-parts-to-host =
      _:
      map (host: den.lib.policy.resolve.to "host" { inherit host; }) (
        builtins.concatMap builtins.attrValues (builtins.attrValues den.hosts)
      );
    schema.flake-mod.includes = [
      den.policies.inputs-to-flake-parts
      den.policies.sources-to-flake-parts
      den.policies.flake-parts-to-host
    ];
    schema.host.include = [ den.policies.inputs-to-flake-parts ];
  };
  flake.den = den;

  #  disabledModules = [ (inputs.flake-file + "/modules/flake-parts.nix") ];

  #perSystem =
  #  { pkgs, ... }:
  #  {
  #    apps =
  #      config.flake-file.apps
  #      |> lib.mapAttrs (
  #        _: f:
  #        let
  #          pkg = f pkgs;
  #        in
  #        {
  #          type = "app";
  #          program = lib.getExe pkg;
  #        }
  #      );

  #    checks.check-flake-file = config.flake-file.check-flake-file pkgs;
  #  };

  flake-file = {
    #  prune-lock.enable = true;
    inputs.flake-file.url = "github:denful/flake-file";
    inputs.rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    preProcess =
      serialized:
      let
        isFlake = name: ((serialized.${name}.flake or true) != false);
        autoFollow =
          name:
          let
            top = lib.attrNames serialized;
            sub = lib.attrNames (inputs.${name}.inputs or { });
            shared = lib.filter (n: n != name && isFlake n) (lib.intersectLists top sub);
          in
          lib.genAttrs shared (s: {
            follows = s;
          });
      in
      lib.mapAttrs (
        name: spec:
        if !(isFlake name) then
          spec
        else
          spec
          // {
            inputs = lib.recursiveUpdate (autoFollow name) (spec.inputs or { });
          }
      ) serialized;
    do-not-edit = ''
      #                                _
      #  __ _ _   _ ___  ___ _   _| |__   ___ _ __
      # / _` | | | / __|/ __| | | | '_ \ / _ \ '__|
      #| (_| | |_| \__ \ (__| |_| | |_) |  __/ |
      # \__,_|\__,_|___/\___|\__, |_.__/ \___|_|
      #                      |___/
                  #          This file is generated by the `write-flake` script. To make changes, edit the source files in `aspects/modules/` and run `nix run .#write-flake`.'';
    outputs = /* nix */ ''
      inputs:
      let
        # Flake-LEVEL input overrides. ./patched-inputs.nix returns an attrset
        # that is merged over `inputs`, so the result is what every module
        # (and flake-level import) sees as `inputs`. Patched sources are built
        # with the pinned system below; empty patched-inputs.nix is a no-op
        # (pkgs is only forced when an override actually uses it).
        imports = with inputs.nixpkgs.lib;
                ./aspects
                |> fileset.fileFilter (file: file.hasExt "nix" && !hasPrefix "_" file.name)
                |> fileset.toList;

        inputsFn =
          finalInputs:
          inputs.flake-parts.lib.mkFlake
            {
              inputs = finalInputs;
              specialArgs = {
                realInputs = inputs;
                lib = inputs.nixpkgs.lib;
              };
            }
            {
              # Import all *.nix files in the ./aspects directory
              # Except ones that start with '_'
              inherit imports;

              _module.args.rootPath = ./.;
            };
        output =
          let
            patchedInputs = (inputsFn inputs).newInputs;
          in
          inputsFn (patchedInputs);
      in
      builtins.removeAttrs output [ "newInputs" ]
    '';

  };

}
