# Signs sketchybar/paneru/kanata with a local certificate and execs them from a
# fixed path, so their TCC grants survive a rebuild.
#
# Two separate things invalidate a grant, and both have to go:
#
#   * TCC keys a non-bundled executable by absolute path (`client_type = 1`),
#     and every rebuild moves the store path. Hence `trustedDir`: each signed
#     binary moves to `signed-bin/`, `bin/<name>` becomes a makeWrapper shim
#     exec'ing `${trustedDir}/<name>`, and activation plants the copy there.
#     The exec resolves before the process exists, so TCC sees the stable path
#     -- and nothing referring to `${pkgs.sketchybar}/bin/sketchybar` has to be
#     repointed, which is the point of doing it here and not per launchd job.
#
#   * the recorded `csreq`. An ad-hoc signature (what nixpkgs applies) has no
#     certificate, so the requirement degrades to a `cdhash` and dies on any
#     content change. A real certificate pins it to the certificate hash
#     instead -- `codesign -d -r-` on a signed output reports
#     `identifier "hello" and certificate root = H"7b3f55..."`, which is a hash
#     comparison and so survives any rebuild of the same program. That is why
#     the certificate must never be regenerated: a new one is a new hash, and
#     every grant made against the old one dies with it.
#
# Signing produces a separate WRAPPER derivation (`mkSignedWrapper`), not an
# `overrideAttrs` on the package. The package itself builds purely and
# substitutes like anything else; only the wrapper is `__noChroot` +
# `allowSubstitutes = false`, and all it does is copy `bin/` through a
# signature. That keeps the identity off the critical path of every Rust and C
# build in the closure, and means a machine without the identity fails on four
# tiny derivations rather than being unable to build the host at all.
#
# The identity is self-signed and generated by `agenix generate`. It cannot be
# the login-keychain one: builds run as `_nixbld*` and `~/Library` is 0700, so
# no keychain there is reachable from a build -- a filesystem permission, not
# the sandbox. `rcodesign` reads the PEM directly and needs no securityd or
# trust store, where `/usr/bin/codesign` refuses an untrusted cert outright.
#
# Split in two, because a switch builds before it activates and so the first
# switch that pulls in the signing half has nothing at `identityFile` yet:
#
#   den.aspects.codesign-identity  the secret, plus the sandbox setting that
#                                  keeps other derivations from reading it.
#                                  Changes no package. Take this first.
#   den.aspects.codesign           the overlay and the activation script. Needs
#                                  the identity already on disk to build -- but
#                                  now only for the wrapper derivations, so a
#                                  first switch no longer rebuilds the world
#                                  before it discovers the key is missing.
#
# So: `agenix generate`, switch with only `codesign-identity`, then add
# `codesign`. They are separate aspects rather than one because dropping a
# combined aspect to break that cycle would drop the secret declaration too,
# leaving nothing to ever deploy the identity.
{
  den,
  lib,
  ...
}:
let
  # `aspects/security/age-scope.nix` joins scope to key with `/`, so this
  # aspect's `secrets.identity` deploys here. Never a store path: the key stays
  # out of the binary cache, and `root:nixbld 0640` is what lets a build read it
  # and nothing else.

  identityFile = "/run/agenix/secrets/codesign/identity";

  # What TCC records as the client for every shimmed program, so it is as
  # permanent as the grants. Not under `/run`: macOS clears it on boot and
  # nix-darwin activation only runs at `darwin-rebuild` time (see
  # `extraModules/darwin/wrappers`), which would leave every shim dangling.
  trustedDir = "/usr/local/dendritic/bin";

  subject = "Dendritic Local Codesign";

  # One recipe for what a codesign identity IS, shared by the `agenix generate`
  # generator below and the `codesign-ci-identity` package -- so a CI runner and
  # a real host can never mint subtly different things. Emits the private key
  # followed by the certificate on stdout, which is exactly the concatenated PEM
  # `rcodesign --pem-file` wants. `certOut`, when set, also keeps the public half
  # at that path (what the generator does, so the leaf hash can be read without
  # decrypting anything).
  mkIdentity =
    pkgs: certOut:
    ''
      work=$(mktemp -d)
      trap 'rm -rf "$work"' EXIT

      # codeSigning EKU is what makes this usable as an identity at all;
      # 1.2.840.113635.100.6.1.14 is Apple's code-signing marker. 20 years,
      # because re-minting invalidates every grant made against the old leaf.
      cat > "$work/openssl.cnf" <<'CNF'
      [req]
      distinguished_name = dn
      x509_extensions = v3
      prompt = no
      [dn]
      CN = ${subject}
      [v3]
      basicConstraints = critical,CA:false
      keyUsage = critical,digitalSignature
      extendedKeyUsage = critical,codeSigning
      1.2.840.113635.100.6.1.14 = critical,DER:0500
      CNF

      ${pkgs.openssl}/bin/openssl req -x509 -newkey rsa:2048 -nodes -days 7300 \
        -config "$work/openssl.cnf" \
        -keyout "$work/key.pem" -out "$work/cert.pem" 2>/dev/null
    ''
    + lib.optionalString (certOut != null) ''
      cp "$work/cert.pem" ${certOut}
    ''
    + ''
      cat "$work/key.pem" "$work/cert.pem"
    '';

  # Entitlements, keyed by the nixpkgs attribute being signed. A plain attrset
  # rather than a `config` option on purpose: signing happens in an overlay, and
  # an overlay that read `config` would close a fixpoint through `pkgs` --
  # `nixpkgs.overlays` is an input to the very `pkgs` that evaluates `config`.
  # `mkSignedWrapper` takes `entitlements` as an argument, so anything building a
  # wrapper by hand can pass whatever it likes; this map is only the defaults for
  # the attributes the overlay signs.
  #
  # Empty for all four today: they are TCC clients, and TCC is keyed by the
  # recorded `csreq` and the executable path, not by entitlements. Kept because
  # entitlements are the thing you reach for the moment one of these needs a
  # capability the ad-hoc signature cannot express.
  entitlementsFor = { };

  # A signed WRAPPER, not a re-signed package. `sign` used to be an
  # `overrideAttrs` that pushed `__noChroot` and `allowSubstitutes = false` onto
  # the package itself, which meant sketchybar/paneru/kanata could never be
  # substituted by anything, on any machine -- every host recompiled all of them,
  # Rust included, and none of them could be built at all without the identity
  # on disk.
  #
  # Here the package builds normally, purely, and substitutes like anything else.
  # Only this `runCommand` is impure, and all it does is copy `bin/` through a
  # signature. What it produces is the same shape the activation script has
  # always planted from:
  #
  #   signed-bin/<name>  the signed binary, which activation copies to trustedDir
  #   bin/<name>         a makeWrapper shim exec'ing ${trustedDir}/<name>
  #   everything else    symlinked straight through from the original
  #
  # `override`/`overrideAttrs` re-enter `mkSignedWrapper`, which is what makes
  # this usable as a module's `package`. paneru's module computes
  # `finalPackage = wrapPaneru (cfg.package.override { enableLua = true; ... })`
  # (nix/_paneru-common.nix), so a wrapper that merely FORWARDED `override` would
  # hand back the unsigned overridden package and drop the signature silently.
  # Re-signing on override means the signing survives whatever the module does to
  # the package afterwards, which is the property the old in-place overlay had
  # and the reason it was written that way.
  mkSignedWrapper =
    pkgs:
    {
      package,
      entitlements ? { },
    }:
    let
      entitlementsFile =
        if entitlements == { } then
          null
        else
          pkgs.writeText "${package.pname or package.name}-entitlements.plist" (
            lib.generators.toPlist { } entitlements
          );
      entitlementsArg =
        lib.optionalString (entitlementsFile != null)
          "--entitlements-xml-path ${entitlementsFile}";
    in
    pkgs.runCommand "${package.name}-signed"
      {
        # Reads a host path that exists on one machine, so it must not be
        # sandboxed and must never be substituted -- a substituted output would
        # be an unsigned build under the same derivation hash. Unchanged from the
        # old `sign`; what changed is how little is now under it.
        __noChroot = true;
        allowSubstitutes = false;
        preferLocalBuild = true;

        nativeBuildInputs = [
          pkgs.rcodesign
          pkgs.makeWrapper
        ];

        # Consumers reach through these. `services.paneru.lua` defaults to
        # `cfg.package.luaModule.lua`, and four call sites in
        # ../wms/paneru/default.nix use `finalPackage.passthru.luaModule`, so
        # dropping passthru breaks evaluation rather than just the signature.
        passthru = (package.passthru or { }) // {
          unsigned = package;
          override = args: mkSignedWrapper pkgs {
            package = package.override args;
            inherit entitlements;
          };
          overrideAttrs = f: mkSignedWrapper pkgs {
            package = package.overrideAttrs f;
            inherit entitlements;
          };
        };
        # `lib.getExe` is used on these, so mainProgram has to survive.
        meta = package.meta or { };
      }
      ''
        mkdir -p "$out/bin" "$out/signed-bin"

        # A wrapper adds a signature; it is not a rebuild. Everything that is
        # not bin/ is the original, so it is symlinked rather than copied.
        shopt -s nullglob
        for entry in ${package}/*; do
          name="$(basename "$entry")"
          # `if`, not `[ ... ] && continue`: the builder runs under `set -e`, so
          # a false test at the end of the body would abort the whole build.
          if [ "$name" = bin ]; then
            continue
          fi
          ln -s "$entry" "$out/$name"
        done

        # Inherited by siblings with no bin/ at all -- paneru's loadable Lua
        # module, for one. Producing no signed-bin/ is the correct outcome there:
        # activation plants what it finds, so a package with nothing to sign
        # contributes nothing.
        if [ ! -d ${package}/bin ]; then
          echo "codesign: ${package} has no bin/, nothing to sign"
          exit 0
        fi

        if [ ! -r ${identityFile} ]; then
          echo "codesign: ${identityFile} unreadable by $(id -un); run 'agenix generate' and switch once" >&2
          exit 1
        fi

        for f in ${package}/bin/*; do
          name="$(basename "$f")"

          # Mach-O by magic number; `file` is not in every stdenv. Anything else
          # -- a shell script, a symlink to one -- is carried through untouched.
          if [ ! -f "$f" ] || [ ! -x "$f" ]; then
            ln -s "$f" "$out/bin/$name"
            continue
          fi
          case "$(od -An -N4 -tx1 -- "$f" | tr -d ' \n')" in
            cffaedfe | cefaedfe | cafebabe | bebafeca) ;;
            *)
              ln -s "$f" "$out/bin/$name"
              continue
              ;;
          esac

          # The identifier is the stable half of the requirement, so it is the
          # name rather than anything version-derived.
          # `--timestamp-url none`: rcodesign otherwise fetches a timestamp token
          # from timestamp.apple.com, which is both a network call in a build and
          # a source of non-determinism. Nothing here needs one -- the
          # requirement TCC stores is the certificate hash.
          rcodesign sign --pem-file ${identityFile} --timestamp-url none \
            --binary-identifier "$name" ${entitlementsArg} \
            "$f" "$out/signed-bin/$name"
          chmod 755 "$out/signed-bin/$name"

          # makeWrapper cannot target ${trustedDir} directly -- assertExecutable
          # rejects a path that only exists after activation -- so it is aimed at
          # the signed binary and then re-pointed.
          makeWrapper "$out/signed-bin/$name" "$out/bin/$name"
          substituteInPlace "$out/bin/$name" --replace-fail "$out/signed-bin/$name" "${trustedDir}/$name"
        done
      '';

  # All four are in this host's TCC database keyed by a store path, which is the
  # whole reason for the list.
  signed = [
    "sketchybar"
    "paneru"
    # `kanata-with-cmd`, not `kanata`: `aspects/input/kanata/_kanata.nix`
    # defaults `programs.kanata.package` to it, because the keybinds in the
    # paneru aspect are all `(t! runasuser ...)` and `cmd` is a build feature.
    # Signing plain `kanata` would sign a package nothing runs.
    "kanata-with-cmd"
    "kanata-vk-agent"
  ];

  present = pkgs: lib.filter (name: pkgs ? ${name}) signed;
in
{
  # `mkSignedWrapper` is the producer: hand it a package and (optionally)
  # entitlements, get back a signed wrapper. Exposed so anything outside this
  # aspect can build one without going through the overlay.
  flake.lib.codesign = {
    inherit
      mkSignedWrapper
      entitlementsFor
      identityFile
      trustedDir
      subject
      ;
  };

  # The public half lands next to the `.age` file (as the wireguard generator
  # does with `.pub`) so the leaf hash can be read without decrypting anything.
  # The recipe itself is `mkIdentity` above, shared with `codesign-ci-identity`.
  den.aspects.agenix-rekey.age.generators.codesign_identity =
    {
      pkgs,
      lib,
      file,
      ...
    }:
    mkIdentity pkgs (lib.escapeShellArg (lib.removeSuffix ".age" file + ".crt"));

  # `nix run .#codesign-ci-identity` -- mint a THROWAWAY identity on stdout, in
  # the same concatenated-PEM form `sign` feeds `rcodesign --pem-file`.
  #
  # This exists for the aarch64-darwin CI runner. `sign` reads `identityFile` at
  # build time and aborts if it is missing, so a runner with no identity cannot
  # build any signed package -- which is every darwin host that includes
  # `den.aspects.codesign`, i.e. the ones `.#ciMatrix.checks.aarch64-darwin`
  # covers. CI plants the output of this at `identityFile` before building (see
  # .github/actions/build-system).
  #
  # Deliberately NOT the host's real identity, and deliberately fine that it is
  # a different certificate every run:
  #
  #   * `sign` sets `allowSubstitutes = false` precisely because the identity is
  #     an impure input that the derivation hash does not cover. A real host
  #     therefore never substitutes a signed path -- it always rebuilds against
  #     its own identity -- so a CI-signed output can never reach one and can
  #     never invalidate a TCC grant. CI is proving these packages *build*, not
  #     producing artefacts anyone installs.
  #   * The alternative -- uploading the host's 20-year signing key as a GitHub
  #     secret -- would put the one key that must never leak, and never change,
  #     on every runner, to no benefit given the point above. The CI action still
  #     accepts a real PEM if one is ever wanted; it just does not need one.
  perSystem =
    { pkgs, lib, ... }:
    lib.optionalAttrs pkgs.stdenv.hostPlatform.isDarwin {
      packages.codesign-ci-identity = pkgs.writeShellApplication {
        name = "codesign-ci-identity";
        runtimeInputs = [ pkgs.coreutils ];
        text = mkIdentity pkgs null;
      };
    };

  # Deliberately its own aspect, and the only one a host needs for the first
  # switch. `codesign` below cannot build until the identity is already deployed
  # (a switch builds before it activates), and if the secret were declared on
  # `codesign` itself then dropping that aspect to break the cycle would drop the
  # secret with it -- nothing would ever deploy the identity. Included on its own
  # this is inert: it deploys one file and changes no package.
  den.aspects.codesign-identity = {
    includes = [ den.aspects.agenix-rekey ];

    # Pinned rather than defaulted to the aspect name, which would make this
    # `/run/agenix/codesign-identity/identity` and orphan the already-generated
    # `secrets/generated/<host>/codesign/identity.age`.
    secretScope = "codesign";

    secrets.identity = {
      generator.script = "codesign_identity";
      mode = "0640";
      group = "nixbld";
    };

    # Belongs with the secret, because it is what stops every OTHER derivation
    # reading it. `sandbox = false` (the nix-darwin default, and what this host
    # ran) means every build sees the real filesystem as `_nixbld*`, and
    # `identityFile` is `0640 root:nixbld` precisely so a build can read it --
    # which means ANY derivation built here could read the private key, not just
    # the four that get signed.
    #
    # `relaxed` closes that: sandboxed builds see no host paths, and only
    # derivations setting `__noChroot = true` are exempt -- which `sign` above
    # already does. Note what is deliberately absent: an `extra-sandbox-paths`
    # entry for the identity. That would mount the key into every sandboxed
    # build and hand it straight back to the derivations this keeps it from.
    #
    # Not airtight: `__noChroot` is honoured for anything a trusted user builds,
    # so a hostile package could set it too. It narrows the set from "everything
    # you build" to "things that visibly opt out of the sandbox", which is
    # greppable. The cost is real -- darwin builds are unsandboxed by default
    # because plenty of packages fail under it, so expect some breakage.
    darwin.nix.settings.sandbox = "relaxed";
  };

  den.aspects.codesign = {
    includes = [ den.aspects.codesign-identity ];

    # Sorted last: `aspects/tooling/overlays.nix` orders overlays by attribute
    # name, and `paneru`/`kanata-vk-agent` only exist once their own overlays
    # have run.
    overlays.zzz-codesign = [
      (
        final: prev:
        lib.genAttrs (present prev) (
          name:
          mkSignedWrapper final {
            package = prev.${name};
            entitlements = entitlementsFor.${name} or { };
          }
        )
      )
    ];

    darwin =
      { config, pkgs, ... }:
      {
        # What gets PLANTED, as opposed to `signed` above which is what gets
        # signed. They are different questions and cannot share a list.
        #
        # `pkgs.<name>` is the wrong source: a module usually runs a derived
        # package, not the attribute the overlay named. `services.paneru` builds
        # `paneru-with-lua` via `.override` and then wraps it for `LUA_PATH`, so
        # this host's closure holds three paths carrying `signed-bin/paneru` --
        # the base build, the lua build, and the wrapper -- and `${pkgs.paneru}`
        # is the lua-LESS one. Planting that put a paneru with no lua at the
        # shim's target.
        #
        # Walking the closure for `signed-bin/` does not disambiguate either:
        # there are four `sketchybar` and three `kanata` paths in it, counting
        # `.override` variants and `home-manager-path` (a buildEnv that
        # aggregates them). Nothing in the store says which one runs.
        #
        # The config does. These are the packages the launchd jobs actually
        # exec, and a wrapper package carries `signed-bin` through as a symlink
        # to the real build -- so taking the final package gets the right binary
        # without touching a single launchd job. `or null` throughout: a host
        # without one of these modules simply contributes nothing.
        system.activationScripts.extraActivation.text =
          let
            # Gated on `enable`, not written as `x.finalPackage or null`. These
            # options exist even where the module is switched off, so a bare
            # read still hits an option with no value defined and aborts the
            # whole evaluation -- which is exactly what the `assessment`
            # specialisation does, since it excludes sketchybar/paneru/kanata.
            fromUser = user: [
              {
                on = user.services.paneru.enable or false;
                get = _: user.services.paneru.finalPackage;
              }
              {
                on = user.programs.sketchybar.enable or false;
                get = _: user.programs.sketchybar.finalPackage;
              }
              {
                on = user.programs.kanata.enable or false;
                get = _: user.programs.kanata.package;
              }
            ];

            runs =
              map (e: e.get null) (
                lib.filter (e: e.on) (lib.concatMap fromUser (lib.attrValues (config.home-manager.users or { })))
              )
              # No override variant of this one exists, so the plain attribute
              # is unambiguous.
              ++ lib.optional (pkgs ? kanata-vk-agent) pkgs.kanata-vk-agent;
          in
          ''
            install -d -m 0755 ${trustedDir}
            for src in ${lib.concatMapStringsSep " " (p: "${p}/signed-bin/*") runs}; do
              # A source can legitimately carry no `signed-bin` -- a package with
              # no `bin/` signs nothing. Skip rather than fail the whole
              # activation on an unmatched glob.
              [ -e "$src" ] || continue

              codesignName=$(basename "$src")

              # Skip an unchanged binary. Not for speed -- the copy is a few
              # milliseconds -- but so that a running program is only replaced
              # when it actually differs, and so the log says what changed.
              if cmp -s "$src" "${trustedDir}/$codesignName"; then
                continue
              fi

              # Staged and renamed because a running executable cannot be written
              # in place; rename leaves the running process on its own vnode.
              install -m 0755 "$src" ${trustedDir}/.staged
              mv -f ${trustedDir}/.staged "${trustedDir}/$codesignName"
              echo "codesign: planted $codesignName in ${trustedDir}"
            done
          '';
      };
  };
}
