# This file is generated by `nix run .#write-flake`. To make changes, edit the
# `ff.*` declarations in the aspects listed under `dev` in ../../partition-map.nix.
#
# It exists only to hold inputs and their lock: the root flake reads
# `.inputs` out of it (see aspects/framework/partitions.nix) and never calls
# `outputs`. `nixpkgs` and every shared `follows` target are pinned to the
# root flake's locked rev so the two locks cannot drift; each is dropped
# again before the inputs are merged into the partition, and is here purely
# so the inputs below can `follows` it -- a `follows` cannot reach the
# parent flake.
{
  outputs = _: { };

  inputs = {
    den-diagram = {
      url = "github:denful/den-diagram";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    deploy-rs = {
      url = "github:serokell/deploy-rs";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-github-actions = {
      url = "github:nix-community/nix-github-actions";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nixpkgs.url = "github:nixos/nixpkgs/59ea0b1c043c463e39fcb3cfb9a5c8bcf0777c72";
  };
}
