# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  alx-wol = {
    pname = "alx-wol";
    version = "alx-wol-3.3";
    src = fetchFromGitHub {
      owner = "AndiWeiss";
      repo = "alx-wol";
      rev = "alx-wol-3.3";
      fetchSubmodules = false;
      sha256 = "sha256-Y0RxY6SaBUANSL52uCMDZX/1Ufz4Cu1N1hKXO76HrDM=";
    };
  };
  app_font = {
    pname = "app_font";
    version = "cce60f7e80a42d0a2d20200c6aa3591e6844ceca";
    src = fetchgit {
      url = "https://github.com/kvndrsslr/sketchybar-app-font";
      rev = "cce60f7e80a42d0a2d20200c6aa3591e6844ceca";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-kFKX41tsSFr0kWlXtyrVpy7Y7o3lnBtt+JUybgoxvM0=";
    };
    date = "2026-09-29";
  };
  cotabby = {
    pname = "cotabby";
    version = "v0.6.2-beta";
    src = fetchurl {
      url = "https://github.com/fujacob/cotabby/releases/download/v0.6.2-beta/Cotabby.dmg";
      sha256 = "sha256-2sOqH2iI7gw5J8QnvG5PAsb4F4m1DW2uPSQHLIK81Pk=";
    };
  };
  eagle-nvim = {
    pname = "eagle-nvim";
    version = "e99f4e36eaf2b5da076ff4e3e8ee7559127aa9e2";
    src = fetchFromGitHub {
      owner = "soulis-1256";
      repo = "eagle.nvim";
      rev = "e99f4e36eaf2b5da076ff4e3e8ee7559127aa9e2";
      fetchSubmodules = false;
      sha256 = "sha256-Hp15PXQ62fYm9cTtt4m3i3R31RlW6HicEbY+3rzgPxU=";
    };
    date = "2026-08-13";
  };
  flaresolverr = {
    pname = "flaresolverr";
    version = "v3.5.2";
    src = dockerTools.pullImage {
      imageName = "ghcr.io/flaresolverr/flaresolverr";
      imageDigest = "sha256:c80ae007ce2ccdcd217a12426e4f039ef763ff90738c808d38810c3e59323767";
      sha256 = "sha256-9ws2xB9Gzt9mdjCKe44SUPY9LXdgcuY3NtCTLFYMoAo=";
      finalImageTag = "v3.5.2";
    };
  };
  ghostty-tip = {
    pname = "ghostty-tip";
    version = "8f0dd3709050b1026f6324368805033197d8b4a5";
    src = fetchurl {
      url = "https://tip.files.ghostty.org/8f0dd3709050b1026f6324368805033197d8b4a5/Ghostty.dmg";
      sha256 = "sha256-/rj1kVJ9TDxlvh5k9WvAwPoqvqA/PKJnbt9wu9vLUW4=";
    };
  };
  helium_linux = {
    pname = "helium_linux";
    version = "0.19.2.1";
    src = fetchTarball {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.19.2.1/helium-0.19.2.1-x86_64_linux.tar.xz";
      sha256 = "sha256-GsscpSDD4WojV7uu1wps2HEmkJzOZRYR90rrVDIjCD8=";
    };
  };
  helium_macos = {
    pname = "helium_macos";
    version = "0.19.2.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-macos/releases/download/0.19.2.1/helium_0.19.2.1_arm64-macos.dmg";
      sha256 = "sha256-wH2rnBVxz2jPhWs1xtC/IcLPU/d8QyRRYwGOeICU6/E=";
    };
  };
  jankyborders = {
    pname = "jankyborders";
    version = "a7297ca7d1933f3a30b12e8f10750e8d84eeee1e";
    src = fetchgit {
      url = "https://github.com/felixkratz/jankyborders";
      rev = "a7297ca7d1933f3a30b12e8f10750e8d84eeee1e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-j4hdW7JXTmSrE4bwlOkUYxA32AD011za7dmItwwIvyg=";
    };
    date = "2026-05-14";
  };
  kanata-tray = {
    pname = "kanata-tray";
    version = "v0.8.0";
    src = fetchFromGitHub {
      owner = "rszyma";
      repo = "kanata-tray";
      rev = "v0.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-RTLFDB/irtEhEHwarROGmS4jNdRhruU1JKen48ADzZg=";
    };
  };
  lspmux = {
    pname = "lspmux";
    version = "18861f9d59e74ece8d867772cf07fa302c2dae98";
    src = fetchgit {
      url = "https://codeberg.org/p2502/lspmux.git";
      rev = "18861f9d59e74ece8d867772cf07fa302c2dae98";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-OchqUe8GdBPL6tE3zpdaThfhzYZhYluagz1yXiexFT0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-OchqUe8GdBPL6tE3zpdaThfhzYZhYluagz1yXiexFT0=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-03-11";
  };
  pam_rssh = {
    pname = "pam_rssh";
    version = "v1.2.2-rc2";
    src = fetchFromGitHub {
      owner = "z4yx";
      repo = "pam_rssh";
      rev = "v1.2.2-rc2";
      fetchSubmodules = true;
      sha256 = "sha256-y25d7gccIdatEDycieRtXfWOqzkfzZBWOUEKS5AXPb8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-y25d7gccIdatEDycieRtXfWOqzkfzZBWOUEKS5AXPb8=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  proton-ge-bin = {
    pname = "proton-ge-bin";
    version = "GE-Proton11-7";
    src = fetchTarball {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton11-7/GE-Proton11-7-x86_64.tar.gz";
      sha256 = "sha256-ftW0vE45v2JsbaYqo/So0ZFfvdtakHX0XEXEE4TdxLk=";
    };
  };
  sketchybar = {
    pname = "sketchybar";
    version = "5f358ec94d117d3e0ccc515b21fafa325940ab2d";
    src = fetchFromGitHub {
      owner = "felixkratz";
      repo = "sketchybar";
      rev = "5f358ec94d117d3e0ccc515b21fafa325940ab2d";
      fetchSubmodules = false;
      sha256 = "sha256-ks2S0JrcLBZqZ4b7P/kNdSOoYpJ96QytVPjE00gxRpg=";
    };
    date = "2026-09-16";
  };
  vscode-kanata = {
    pname = "vscode-kanata";
    version = "ed1bd6d7520e0b405685a21b978279d0a611386f";
    src = fetchgit {
      url = "https://github.com/rszyma/vscode-kanata.git";
      rev = "ed1bd6d7520e0b405685a21b978279d0a611386f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-EvTLXOIUGXFsNUV/uiLy4VA/XEuImQ1dHkpI9jz5ogs=";
    };
    date = "2026-10-08";
  };
  zotero-actions-tags = {
    pname = "zotero-actions-tags";
    version = "2.6.1";
    src = fetchurl {
      url = "https://github.com/windingwind/zotero-actions-tags/releases/download/v2.6.1/actions-and-tags-for-zotero.xpi";
      sha256 = "sha256-lVm1FVQylurzuldELohEEHEgNBHm5jr8GjHfTVdq65U=";
    };
  };
  zotero-aria = {
    pname = "zotero-aria";
    version = "v0.7.5";
    src = fetchurl {
      url = "https://github.com/lifan0127/ai-research-assistant/releases/download/v0.7.5/aria.xpi";
      sha256 = "sha256-xqki7703PPYdHqUwDGyG3+nBfabYVfnGz10EJ2oeH7c=";
    };
  };
  zotero-attanger = {
    pname = "zotero-attanger";
    version = "v1.5.0";
    src = fetchurl {
      url = "https://github.com/MuiseDestiny/zotero-attanger/releases/download/v1.5.0/zotero-attanger.xpi";
      sha256 = "sha256-3/dpVWSoBnb8cGSHtAw5+4E8dPXUhw91LIeGWCpxW6c=";
    };
  };
  zotero-better-bibtex = {
    pname = "zotero-better-bibtex";
    version = "9.0.71";
    src = fetchurl {
      url = "https://github.com/retorquere/zotero-better-bibtex/releases/download/v9.0.71/zotero-better-bibtex-9.0.71.xpi";
      sha256 = "sha256-v2GhaQ3IorerCb6d4siZhvT7bUlcgkB9ibECsm+6qdU=";
    };
  };
  zotero-better-notes = {
    pname = "zotero-better-notes";
    version = "3.3.3";
    src = fetchurl {
      url = "https://github.com/windingwind/zotero-better-notes/releases/download/v3.3.3/better-notes-for-zotero.xpi";
      sha256 = "sha256-SNQmAYM4vs14xx+FFZw2wDu+P2KZq1pWQJniN5CwHB4=";
    };
  };
  zotero-notero = {
    pname = "zotero-notero";
    version = "011be2ca9ddc6b34326f7e5ce75089266cbf94bc";
    src = fetchFromGitHub {
      owner = "dvanoni";
      repo = "notero";
      rev = "011be2ca9ddc6b34326f7e5ce75089266cbf94bc";
      fetchSubmodules = false;
      sha256 = "sha256-qvjBHzQTTflW8cafr50yKuUteSctoBXl752nHyV/VmI=";
    };
    date = "2026-08-18";
  };
  zotero-ocr = {
    pname = "zotero-ocr";
    version = "0.9.6";
    src = fetchurl {
      url = "https://github.com/UB-Mannheim/zotero-ocr/releases/download/0.9.6/zotero-ocr-0.9.6.xpi";
      sha256 = "sha256-k2JzTfNfTVOmDI7GOkE0o1ebvCI6XZfYSI7KbcjJ4L8=";
    };
  };
  zotero-papersgpt = {
    pname = "zotero-papersgpt";
    version = "papersgpt-v1.7.0";
    src = fetchurl {
      url = "https://github.com/papersgpt/papersgpt-for-zotero/releases/download/papersgpt-v1.7.0/papersgpt-v1.7.0.xpi";
      sha256 = "sha256-qaeloEFR7YfhFF4+VxYQAK2pveN2ui4cterFwyVbgqk=";
    };
  };
  zotero-zotlit = {
    pname = "zotero-zotlit";
    version = "2.2.0-beta.1";
    src = fetchurl {
      url = "https://github.com/aidenlx/zotlit/releases/download/zt-2.2.0-beta.1/zotlit-zotero-2.2.0-beta.1.xpi";
      sha256 = "sha256-t4suYgy5WpSWO4dQXmlqjK97+9AcUYTFYID0HLYpNFc=";
    };
  };
}
