# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cursor_shader = {
    pname = "cursor_shader";
    version = "fb494d124d6b16a2472ae1815f70c48ece38f9e4";
    src = fetchgit {
      url = "https://github.com/Crackerfracks/synesthaxia.glsl";
      rev = "fb494d124d6b16a2472ae1815f70c48ece38f9e4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-za6zGqiVDF0Ph+hE3m6Mcr3K1thQpiMmUG0yPmzn6m4=";
    };
    date = "2025-06-29";
  };
  deadlock-mod-manager = {
    pname = "deadlock-mod-manager";
    version = "v0.18.0";
    src = fetchurl {
      url = "https://github.com/deadlock-mod-manager/deadlock-mod-manager/releases/download/v0.18.0/deadlock-mod-manager.flatpak";
      sha256 = "sha256-azZfebt3mHhiasssSCBtB95pvLianjwbLYB+vhV1DYU=";
    };
  };
  game-devices-udev-rules = {
    pname = "game-devices-udev-rules";
    version = "main";
    src = fetchTarball {
      url = "https://github.com/fabiscafe/game-devices-udev/archive/main.tar.gz";
      sha256 = "sha256-LXTlnimC0Xw+4YwUc151ePOaktdqlUDAdX01L21wmO0=";
    };
  };
  ghostty = {
    pname = "ghostty";
    version = "tip";
    src = fetchFromGitHub {
      owner = "ghostty-org";
      repo = "ghostty";
      rev = "tip";
      fetchSubmodules = false;
      sha256 = "sha256-dnk4veKoZpWQPnwTaCtpfaE4WQi0tg1JSpM4/P/Rfe0=";
    };
  };
  helium_linux = {
    pname = "helium_linux";
    version = "0.11.7.1";
    src = fetchTarball {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.11.7.1/helium-0.11.7.1-x86_64_linux.tar.xz";
      sha256 = "sha256-9y9vviF8iBewUSVMVpOW1dFX5GmSDQSR/kH/OlOvCKg=";
<<<<<<< HEAD
    };
  };
  helium_macos = {
    pname = "helium_macos";
    version = "0.11.7.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-macos/releases/download/0.11.7.1/helium_0.11.7.1_arm64-macos.dmg";
      sha256 = "sha256-jbu/w3/GYC60Gs0ueeECrbeDDSLAoXFManquIpw0VvM=";
=======
>>>>>>> 9dbf96b4b (change and update)
    };
  };
  icon_map = {
    pname = "icon_map";
    version = "v2.0.60";
    src = fetchurl {
      url = "https://github.com/kvndrsslr/sketchybar-app-font/releases/download/v2.0.60/icon_map.sh";
      sha256 = "sha256-seYKDv4fFmxryBk9j+RLk3WA3LFPG9zN/ULMvIDNAlQ=";
    };
  };
  jankyborders = {
    pname = "jankyborders";
    version = "a56a76a8a6ed77325f03655b23fcf525144d120b";
    src = fetchgit {
      url = "https://github.com/felixkratz/jankyborders";
      rev = "a56a76a8a6ed77325f03655b23fcf525144d120b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-odhoKy+aABfv19fxaINWtmY6hbmYyeQzWzxgOlD8ONE=";
    };
    date = "2026-01-10";
  };
  kanata = {
    pname = "kanata";
    version = "v1.11.0";
    src = fetchFromGitHub {
      owner = "jtroo";
      repo = "kanata";
      rev = "v1.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-7rGV0nfI/ntvByz3NQs/2Sa2q/Ml8O3XRD14Mbt5fIU=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-7rGV0nfI_ntvByz3NQs_2Sa2q_Ml8O3XRD14Mbt5fIU=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  proton-ge-bin = {
    pname = "proton-ge-bin";
    version = "GE-Proton10-34";
    src = fetchTarball {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton10-34/GE-Proton10-34.tar.gz";
      sha256 = "sha256-lzPsYYcrp5NoT3B0WFj3o10Z7tXx7xva1wEP3edeuqM=";
    };
  };
<<<<<<< HEAD
  sketchybar = {
    pname = "sketchybar";
    version = "v2.23.0";
    src = fetchFromGitHub {
      owner = "felixkratz";
      repo = "sketchybar";
      rev = "v2.23.0";
      fetchSubmodules = false;
      sha256 = "sha256-PvKvevsSyRb6OfPWc2+1Bcfj2ngmgeP1URBoBiVeEdk=";
    };
  };
  slskd = {
    pname = "slskd";
    version = "8fb755972514458ed86bb8130bcac01ce18a57e4";
    src = fetchgit {
      url = "https://github.com/slskd/slskd.git";
      rev = "8fb755972514458ed86bb8130bcac01ce18a57e4";
=======
  slskd = {
    pname = "slskd";
    version = "50608eb15eaed8c951eed0599be28df2821c79b3";
    src = fetchgit {
      url = "https://github.com/slskd/slskd.git";
      rev = "50608eb15eaed8c951eed0599be28df2821c79b3";
>>>>>>> 9dbf96b4b (change and update)
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
<<<<<<< HEAD
      sha256 = "sha256-jqkeUuk0F+U7FggWtOAWUXFrF5op9F+u77iW2DRpXvA=";
    };
    extract = {
      "./src/web/package-lock.json" = ./. + "/sha256-jqkeUuk0F+U7FggWtOAWUXFrF5op9F+u77iW2DRpXvA=/./src/web/package-lock.json";
    };date = "2026-05-03";prefetch = {
    "./src/web/package-lock.json" = "sha256-ta9emcPPPiNrPI0a89UxDdS3aymQU/VobRsjWLod6NQ=";
    
    };
=======
      sha256 = "sha256-/bvyHcIRGBuH5eNXeisZWbL/5/J2ZFq9A5Vg2z+B9cw=";
    };
    extract = {
      "./src/web/package-lock.json" = ./. + "/sha256-_bvyHcIRGBuH5eNXeisZWbL_5_J2ZFq9A5Vg2z+B9cw=/./src/web/package-lock.json";
    };date = "2026-05-02";
>>>>>>> 9dbf96b4b (change and update)
  };
  yabai = {
    pname = "yabai";
    version = "f17ef88116b0d988b834bb2801c3caad952cc49d";
    src = fetchgit {
      url = "https://github.com/koekeishiya/yabai";
      rev = "f17ef88116b0d988b834bb2801c3caad952cc49d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-26SXci4u42ztlgfIBFO+US9cETNnQ+/O44C227c3x8w=";
    };
    date = "2026-04-26";
  };
}
