# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  alx-wol = {
    pname = "alx-wol";
    version = "alx-wol-3.1";
    src = fetchFromGitHub {
      owner = "AndiWeiss";
      repo = "alx-wol";
      rev = "alx-wol-3.1";
      fetchSubmodules = false;
      sha256 = "sha256-Sfq1vnf+UXNtSSBjGPe0Ignu6G8clp4RrVpeT8F5Xw8=";
    };
  };
  app_font = {
    pname = "app_font";
    version = "d03b0556e5910c71849fdbcb02863b5ac5fae12a";
    src = fetchgit {
      url = "https://github.com/kvndrsslr/sketchybar-app-font";
      rev = "d03b0556e5910c71849fdbcb02863b5ac5fae12a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-MJovtp+ybJdhc65Xu6MJC381zLh/YrQ0PMLP1OWX2m4=";
    };
    date = "2026-08-15";
  };
  cotabby = {
    pname = "cotabby";
    version = "v0.6.2-beta";
    src = fetchurl {
      url = "https://github.com/fujacob/cotabby/releases/download/v0.6.2-beta/Cotabby.dmg";
      sha256 = "sha256-2sOqH2iI7gw5J8QnvG5PAsb4F4m1DW2uPSQHLIK81Pk=";
    };
  };
  eagle-nvim = {
    pname = "eagle-nvim";
    version = "e99f4e36eaf2b5da076ff4e3e8ee7559127aa9e2";
    src = fetchFromGitHub {
      owner = "soulis-1256";
      repo = "eagle.nvim";
      rev = "e99f4e36eaf2b5da076ff4e3e8ee7559127aa9e2";
      fetchSubmodules = false;
      sha256 = "sha256-Hp15PXQ62fYm9cTtt4m3i3R31RlW6HicEbY+3rzgPxU=";
    };
    date = "2026-08-13";
  };
  helium_linux = {
    pname = "helium_linux";
    version = "0.15.4.1";
    src = fetchTarball {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.15.4.1/helium-0.15.4.1-x86_64_linux.tar.xz";
      sha256 = "sha256-bvePM38HlSm9IaPqlst3HQNKuz+mKtVg4pFA5aQWRhc=";
    };
  };
  helium_macos = {
    pname = "helium_macos";
    version = "0.15.4.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-macos/releases/download/0.15.4.1/helium_0.15.4.1_arm64-macos.dmg";
      sha256 = "sha256-GRX9snfkdi5B9oU5zimzSgY8zjKqdzJZZKVf2K7E9TU=";
    };
  };
  jankyborders = {
    pname = "jankyborders";
    version = "a7297ca7d1933f3a30b12e8f10750e8d84eeee1e";
    src = fetchgit {
      url = "https://github.com/felixkratz/jankyborders";
      rev = "a7297ca7d1933f3a30b12e8f10750e8d84eeee1e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-j4hdW7JXTmSrE4bwlOkUYxA32AD011za7dmItwwIvyg=";
    };
    date = "2026-05-14";
  };
  kanata-tray = {
    pname = "kanata-tray";
    version = "v0.8.0";
    src = fetchFromGitHub {
      owner = "rszyma";
      repo = "kanata-tray";
      rev = "v0.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-RTLFDB/irtEhEHwarROGmS4jNdRhruU1JKen48ADzZg=";
    };
  };
  lspmux = {
    pname = "lspmux";
    version = "18861f9d59e74ece8d867772cf07fa302c2dae98";
    src = fetchgit {
      url = "https://codeberg.org/p2502/lspmux.git";
      rev = "18861f9d59e74ece8d867772cf07fa302c2dae98";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-OchqUe8GdBPL6tE3zpdaThfhzYZhYluagz1yXiexFT0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-OchqUe8GdBPL6tE3zpdaThfhzYZhYluagz1yXiexFT0=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-03-11";
  };
  pam_rssh = {
    pname = "pam_rssh";
    version = "v1.2.1";
    src = fetchFromGitHub {
      owner = "z4yx";
      repo = "pam_rssh";
      rev = "v1.2.1";
      fetchSubmodules = true;
      sha256 = "sha256-yHB6tEQuUFYve6GgAW6VuLSw49q0l0VzgH1vIquPNMQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-yHB6tEQuUFYve6GgAW6VuLSw49q0l0VzgH1vIquPNMQ=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  proton-ge-bin = {
    pname = "proton-ge-bin";
    version = "GE-Proton11-5";
    src = fetchTarball {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton11-5/GE-Proton11-5-x86_64.tar.gz";
      sha256 = "sha256-Sbyi5zXMhPIKSotvL5LEZ2dbDoLpXRcCyuY9TsnBnus=";
    };
  };
  sketchybar = {
    pname = "sketchybar";
    version = "6284ee816601486ace33ca48a0271832eec6de35";
    src = fetchFromGitHub {
      owner = "felixkratz";
      repo = "sketchybar";
      rev = "6284ee816601486ace33ca48a0271832eec6de35";
      fetchSubmodules = false;
      sha256 = "sha256-5tyc/yYzdV/3JTtujuj7le/14XkC7TlN/nZg7tOZsNg=";
    };
    date = "2026-06-04";
  };
  vscode-kanata = {
    pname = "vscode-kanata";
    version = "9792013dba8db8fd1fe9253cd5a730ed09b81da0";
    src = fetchgit {
      url = "https://github.com/rszyma/vscode-kanata.git";
      rev = "9792013dba8db8fd1fe9253cd5a730ed09b81da0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NsR/tWWmE6kUuCVlRt4miGS5oqcE3vhFC7nbN5VLy8Q=";
    };
    date = "2026-08-15";
  };
  zotero-actions-tags = {
    pname = "zotero-actions-tags";
    version = "2.5.2";
    src = fetchurl {
      url = "https://github.com/windingwind/zotero-actions-tags/releases/download/v2.5.2/actions-and-tags-for-zotero.xpi";
      sha256 = "sha256-ASPnaCjkRuyLHIg1gsPQ+hFMxFnl7gNxclSfAOPCxek=";
    };
  };
  zotero-aria = {
    pname = "zotero-aria";
    version = "v0.7.5";
    src = fetchurl {
      url = "https://github.com/lifan0127/ai-research-assistant/releases/download/v0.7.5/aria.xpi";
      sha256 = "sha256-xqki7703PPYdHqUwDGyG3+nBfabYVfnGz10EJ2oeH7c=";
    };
  };
  zotero-attanger = {
    pname = "zotero-attanger";
    version = "1.4.9";
    src = fetchurl {
      url = "https://github.com/MuiseDestiny/zotero-attanger/releases/download/1.4.9/zotero-attanger.xpi";
      sha256 = "sha256-XBBPHfdJG0n+I1zsBwgcRm1yaOFDY1uVTdbWWmMi5Os=";
    };
  };
  zotero-better-bibtex = {
    pname = "zotero-better-bibtex";
    version = "9.0.55";
    src = fetchurl {
      url = "https://github.com/retorquere/zotero-better-bibtex/releases/download/v9.0.55/zotero-better-bibtex-9.0.55.xpi";
      sha256 = "sha256-LZFOuxdMLFkOz/dBppA/GXkGW0J0DzAdk47Cy2wD5NY=";
    };
  };
  zotero-better-notes = {
    pname = "zotero-better-notes";
    version = "3.3.0-beta.5";
    src = fetchurl {
      url = "https://github.com/windingwind/zotero-better-notes/releases/download/v3.3.0-beta.5/better-notes-for-zotero.xpi";
      sha256 = "sha256-SjvJqCkVw/gb77RD5dAVUXXdfyrAXgNjE1vweDoHQM4=";
    };
  };
  zotero-notero = {
    pname = "zotero-notero";
    version = "556359043a4b61df5802b6650cbdbec6450bf9d4";
    src = fetchFromGitHub {
      owner = "dvanoni";
      repo = "notero";
      rev = "556359043a4b61df5802b6650cbdbec6450bf9d4";
      fetchSubmodules = false;
      sha256 = "sha256-hl93l5W1qvW+XXSphvw8/36+xhfbajjIPNPqikWj/+k=";
    };
    date = "2026-05-08";
  };
  zotero-ocr = {
    pname = "zotero-ocr";
    version = "0.9.5.1";
    src = fetchurl {
      url = "https://github.com/UB-Mannheim/zotero-ocr/releases/download/0.9.5.1/zotero-ocr-0.9.5.1.xpi";
      sha256 = "sha256-8QCz5gy087tpFmV261fnb3ACsk/1JkjCpoJ9aLU1r44=";
    };
  };
  zotero-papersgpt = {
    pname = "zotero-papersgpt";
    version = "papersgpt-v1.1.0";
    src = fetchurl {
      url = "https://github.com/papersgpt/papersgpt-for-zotero/releases/download/papersgpt-v1.1.0/papersgpt-v1.1.0.xpi";
      sha256 = "sha256-/vyE3wemCGn4ncEFLrRiK8qU+XN2RrK6DcJGnJ7/ip8=";
    };
  };
  zotero-zotlit = {
    pname = "zotero-zotlit";
    version = "2.0.1";
    src = fetchurl {
      url = "https://github.com/aidenlx/zotlit/releases/download/zt-2.0.1/zotlit-zotero-2.0.1.xpi";
      sha256 = "sha256-vxkBUOWmPJRwVMzmSje1M1iJ8J8dFtAXUaAqR7pe03U=";
    };
  };
}
