# This file is generated by `nix run .#write-flake`. To make changes, edit the
# `ff.*` declarations in the aspects listed under `darwin` in ../../partition-map.nix.
#
# It exists only to hold inputs and their lock: the root flake reads
# `.inputs` out of it (see aspects/framework/partitions.nix) and never calls
# `outputs`. `nixpkgs` and every shared `follows` target are pinned to the
# root flake's locked rev so the two locks cannot drift; each is dropped
# again before the inputs are merged into the partition, and is here purely
# so the inputs below can `follows` it -- a `follows` cannot reach the
# parent flake.
{
  outputs = _: { };

  inputs = {
    crane.url = "github:ipetkov/crane/508ff4829aefddee8ea62291e86b144b58365724";
    homebrew-cask = {
      url = "github:homebrew/homebrew-cask";
      flake = false;
    };
    homebrew-core = {
      url = "github:homebrew/homebrew-core";
      flake = false;
    };
    homebrew-speedtest = {
      url = "github:teamookla/homebrew-speedtest";
      flake = false;
    };
    homebrew-typewhisper = {
      url = "github:typewhisper/homebrew-tap";
      flake = false;
    };
    idris2Packages.url = "github:mattpolzin/nix-idris2-packages";
    nix-homebrew.url = "github:zhaofengli/nix-homebrew";
    nixpkgs.url = "github:nixos/nixpkgs/59ea0b1c043c463e39fcb3cfb9a5c8bcf0777c72";
    paneru = {
      url = "github:auscyber/paneru?ref=add-lua-stuff";
      inputs = {
        crane.follows = "crane";
        nixpkgs.follows = "nixpkgs";
      };
    };
  };
}
