# This file is generated by `nix run .#write-flake`. To make changes, edit the
# `ff.*` declarations in the aspects listed under `darwin` in ../../partition-map.nix.
#
# It exists only to hold inputs and their lock: the root flake reads
# `.inputs` out of it (see aspects/framework/partitions.nix) and never calls
# `outputs`. `nixpkgs` and every shared `follows` target are pinned to the
# root flake's locked rev so the two locks cannot drift; each is dropped
# again before the inputs are merged into the partition, and is here purely
# so the inputs below can `follows` it -- a `follows` cannot reach the
# parent flake.
{
  outputs = _: { };

  inputs = {
    home-manager.url = "github:nix-community/home-manager/e705714e918c3b11affcdd15db2cbe3a070420a0";
    homebrew-cask = {
      url = "github:homebrew/homebrew-cask";
      flake = false;
    };
    homebrew-core = {
      url = "github:homebrew/homebrew-core";
      flake = false;
    };
    homebrew-speedtest = {
      url = "github:teamookla/homebrew-speedtest";
      flake = false;
    };
    homebrew-typewhisper = {
      url = "github:typewhisper/homebrew-tap";
      flake = false;
    };
    idris2Packages.url = "github:mattpolzin/nix-idris2-packages";
    my-nur = {
      url = "github:auscyber/nur-packages";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-homebrew.url = "github:zhaofengli/nix-homebrew";
    nixpkgs.url = "github:nixos/nixpkgs/9bc02893134c733dd85de46ee4fb2fac696b5529";
    nur = {
      url = "github:nix-community/NUR";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    rift.url = "github:auscyber/rift";
    zen-browser = {
      url = "github:0xc000022070/zen-browser-flake";
      inputs = {
        home-manager.follows = "home-manager";
        nixpkgs.follows = "nixpkgs";
      };
    };
  };
}
