#!/bin/sh
stack install :xmonad
set -e
PROJ=${PROJ:-my-xmonad}
stack build :$PROJ --verbosity error
stack install :$PROJ  --local-bin-path bin/ --verbosity error
if [[ "$(readlink $1)" != "bin/$PROJ" ]];
then
    {
    rm $1
    ln -s bin/$PROJ "$1"
} || true
fi
