{
  inputs,
  lib,
  self,
  config,
  withSystem,
  rootPath,
  realInputs,
  ...
}:
let
  inherit (lib) mapAttrs;
  patchedInputModule =
    {
      config,
      name,
      ...
    }:
    {
      options = {
        src = lib.mkOption {
          type = lib.types.raw;
          default = realInputs.${name}.sourceInfo;
          description = "Source flake to patch (usually another `inputs.<x>`).";
        };
        autoIncludePatches = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = ''
            If true, automatically include any patch files found in
            `./patches/<name>/*.patch` (where `<name>` is the key of this input).
            This is convenient for local development, but may be undesirable if
            you want to control exactly which patches are applied.
          '';
        };
        isInput = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = ''
            If true, this patched flake is added to the `inputs` of the flake
            module. If false, it is built but not added to `inputs`.
          '';
        };
        hash = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          default = patchHashes.${name} or null;
          description = ''
            SRI hash of the *patched* source tree, making it a fixed-output
            derivation: the store path then depends only on the content, not
            on the system that built it, and it can be substituted from a
            binary cache instead of rebuilt on every machine.

            Defaults to the entry for this input in `./patches/hashes.json`.
            Refresh with `nix run .#update-patch-hashes` after changing a
            patch or bumping the upstream input — a stale hash fails the
            build with a hash mismatch.

            `null` opts out: the tree is built locally, unsubstitutable, and
            its path varies with the building system (the old behaviour).
          '';
        };
        patches = lib.mkOption {
          type = lib.types.listOf lib.types.path;
          default =
            if config.autoIncludePatches then
              with lib;
              ../../patches/${name}
              |> fileset.fileFilter (file: file.hasExt "patch" && !hasPrefix "_" file.name)
              |> fileset.toList
            else
              [ ];

          description = "Patch files (unified diffs) applied in order.";
        };
        prePatch = lib.mkOption {
          type = lib.types.lines;
          default = "";
        };
        postPatch = lib.mkOption {
          type = lib.types.lines;
          default = "";
        };
        enable = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = ''
            Enable this patched input. If false, the input is not built or
            added to `inputs`.
          '';
        };
      };
    };

  # The patch implementation lives in ../../lib/patched-inputs.nix as a plain
  # function so flake.nix can call it WITHOUT running the module system (see
  # that file's header). This module and flake.nix therefore share one
  # implementation; the only thing that differs is where the specs come from —
  # here, the live `config.patchedInputs`; there, the generated
  # ../../patched-inputs.nix.
  impl = import ../../lib/patched-inputs.nix {
    inherit lib rootPath;
    inputs = realInputs;
    inherit (config) noUnify patchSystem;
    patchSpecs = lib.mapAttrs (_: v: {
      inherit (v)
        patches
        prePatch
        postPatch
        isInput
        src
        hash
        ;
    }) config.patchedInputs;
  };
  inherit (impl)
    toBuild
    patchedDrvs
    patchedDrvsUnhashed
    hasPatches
    ;

  # Serialised form of the live patch config, written verbatim into
  # ./patched-inputs.nix by `nix run .#write-patched-inputs`. Paths are emitted
  # relative to the flake root so the generated file stays source-relative
  # (./patches/...) rather than baking in /nix/store paths.
  generatedPatchedInputs =
    let
      relPath =
        p:
        let
          s = toString p;
          root = toString rootPath;
        in
        if lib.hasPrefix root s then "." + lib.removePrefix root s else s;
      entry =
        name: v:
        let
          ps = map relPath v.patches;
        in
        if ps == [ ] then
          "  ${name}.patches = [ ];"
        else
          "  ${name}.patches = [\n${lib.concatMapStringsSep "\n" (x: "    ${x}") ps}\n  ];";
      body = lib.concatStringsSep "\n\n" (
        lib.mapAttrsToList entry (lib.filterAttrs (_: v: v.isInput) config.patchedInputs)
      );
    in
    ''
      # GENERATED by `nix run .#write-patched-inputs` — do not edit by hand.
      #
      # The patch configuration flake.nix needs BEFORE it can evaluate the
      # flake-parts module system. Everything else is derived purely at eval
      # time: `src` from the flake input, `hash` from ./patches/hashes.json,
      # and the auto-unified set from ./flake.lock.
      #
      # `checks.patched-inputs-generated-current` fails if this drifts from the
      # aspects' own declarations.
      {
      ${body}
      }
    '';

  # Recorded SRI hashes, read here too so the `hash` option default keeps
  # working (the implementation reads the same file for its own default).
  patchHashes =
    let
      file = ../../patches/hashes.json;
      ignore = builtins.getEnv "PATCH_HASHES" == "ignore";
    in
    if ignore || !builtins.pathExists file then { } else builtins.fromJSON (builtins.readFile file);

  patchInputScript =
    pkgs:
    pkgs.writeShellApplication {
      name = "patch-input";
      runtimeInputs = [
        pkgs.git
        pkgs.coreutils
      ];
      text = ''
        set -euo pipefail
        input="''${1:-}"
        patchName="''${2:-edit}"
        if [ -z "$input" ]; then
        	echo "usage: patch-input <input-name> [patch-name]" >&2
        	exit 2
        fi
        repo="$PWD"
        if [ ! -e "$repo/flake.nix" ]; then
        	echo "error: run from the flake root (no flake.nix in $repo)" >&2
        	exit 2
        fi

        echo "Resolving source of input '$input'…"
        src="$(nix eval --impure --raw --expr \
        	"builtins.toString (builtins.getFlake (toString $repo)).inputs.\"$input\"")"
        echo "  $src"

        work="$(mktemp -d -t "patch-$input.XXXXXX")"
        cp -R "$src/." "$work/"
        chmod -R u+w "$work"
        cd "$work"
        git init -q
        git add -A
        GIT_AUTHOR_NAME=patch GIT_AUTHOR_EMAIL=patch@local \
        	GIT_COMMITTER_NAME=patch GIT_COMMITTER_EMAIL=patch@local \
        	git commit -q -m pristine

        cat <<EOF

        Editing a copy of '$input' in:
          $work
        Make your changes, then exit this shell ('exit' / Ctrl-D) to capture the diff.
        Exit non-zero (e.g. 'exit 1') to abort without writing a patch.

        EOF

        out="$repo/patches/$input/$patchName.patch"
        if [ -e "$out" ]; then
        	git apply "$out"
        fi
        set +e
        "''${SHELL:-/bin/sh}"
        shellrc=$?
        set -e
        if [ "$shellrc" -ne 0 ]; then
        	echo "aborted (shell exited $shellrc); no patch written." >&2
        	exit "$shellrc"
        fi

        git add -A
        mkdir -p "$(dirname "$out")"
        # --no-ext-diff: bypass any external difftool (e.g. difftastic) from the
        # user's global git config, which would emit non-applicable output.
        # diff.noprefix=false: keep a/ b/ prefixes so `patch -p1` (applyPatches) works.
        git -c diff.noprefix=false diff --no-ext-diff --cached --binary HEAD >"$out"
        if [ ! -s "$out" ]; then
        	rm -f "$out"
        	echo "no changes detected; nothing written." >&2
        	exit 0
        fi
        echo "wrote $out"
        echo "Add it to patchedInputs.\"$input\".patches and rebuild."
      '';
    };

  # `nix run .#update-patch-hashes`
  #
  # Records the SRI hash of each patched tree in ./patches/hashes.json, which
  # feeds the `hash` option and so makes the trees fixed-output. Re-run after
  # changing a patch or bumping a patched input: the recorded hash covers the
  # patched *content*, so any change to either invalidates it and the build then
  # fails with a hash mismatch until refreshed.
  #
  # The unhashed derivations are interpolated below, so `nix run` builds them as
  # dependencies of this script — no flake output to plumb, and no dependency on
  # the (possibly stale) hashes already on disk.
  updateHashesScript =
    pkgs:
    let
      entries = lib.mapAttrsToList (n: drv: "${n} ${drv}") (patchedDrvsUnhashed pkgs);
    in
    pkgs.writeShellApplication {
      name = "update-patch-hashes";
      runtimeInputs = [
        pkgs.jq
        pkgs.coreutils
      ];
      text = ''
        set -euo pipefail
        repo="$PWD"
        if [ ! -e "$repo/flake.nix" ]; then
        	echo "error: run from the flake root (no flake.nix in $repo)" >&2
        	exit 2
        fi

        out="$repo/patches/hashes.json"
        tmp="$(mktemp)"
        trap 'rm -f "$tmp" "$tmp.new"' EXIT
        echo '{}' >"$tmp"

        while read -r name path; do
        	[ -n "$name" ] || continue
        	hash="$(nix hash path --sri "$path")"
        	echo "  $name  $hash"
        	jq --arg n "$name" --arg h "$hash" '.[$n] = $h' "$tmp" >"$tmp.new"
        	mv "$tmp.new" "$tmp"
        done <<-'ENTRIES'
        	${lib.concatStringsSep "\n\t" entries}
        ENTRIES

        mkdir -p "$(dirname "$out")"
        jq -S . "$tmp" >"$out"
        echo "wrote $out"
      '';
    };
in
{
  options.patchSystem = lib.mkOption {
    type = lib.types.str;
    # No hardcoded system. Under impure eval `builtins.currentSystem` is the
    # host, so the trees build wherever they're evaluated. Under pure eval the
    # builtin is absent and we fall back to the flake's *own* first declared
    # system — derived, not a magic literal.
    #
    # For an input with a recorded `hash` the tree is fixed-output, so this
    # picks nothing about the resulting store path — every system produces the
    # identical output — it only decides which host can *build* it on a cold
    # cache (a warm cache substitutes it cross-system regardless). For an input
    # without a hash it still determines the path, as before.
    default = builtins.currentSystem or "x86_64-linux"; # or (builtins.head config.systems);
    defaultText = lib.literalExpression "builtins.currentSystem or (builtins.head config.systems)";
    description = ''
      System whose `pkgs` *builds* the patched source trees. See the comment in
      `patch-inputs.nix`; with a recorded `hash` this does not affect the output
      path, only which host can build on a cold cache.
    '';
  };

  options.noUnify = lib.mkOption {
    type = lib.types.listOf lib.types.str;
    default = [ ];
    description = ''
      Input names to exclude from automatic input-unification re-eval — an escape
      hatch for a flake that does not survive `patchFlake`'s lock-resolver. Only
      removes AUTO-unified inputs (those pulled in because they transitively depend
      on a patched input); an input explicitly listed in `patchedInputs` is always
      built, since it may carry patches.
    '';
  };

  options.patchedInputs = lib.mkOption {
    default = { };
    description = ''
      Flake inputs to patch with local diffs. Each entry is applied with
      `pkgs.applyPatches` (which FAILS the build if a patch no longer applies)
      and re-loaded as a flake via flake-compat, then merged into the `inputs`
      argument seen by home-manager modules — reference it as `inputs.<name>`
      (e.g. `inputs.zen-browser-patched.homeModules.default`).

      Produce/refresh a patch with `nix run .#patch-input -- <name>`.

      Note: `inputs` at the flake-module level is a flake-parts specialArg bound
      to `self.inputs` and cannot be shadowed there; this injection happens in
      the home-manager scope (where patched flakes' modules are consumed and a
      per-system `pkgs` is available to build the patch).
    '';
    example = lib.literalExpression ''
      {
        zen-browser-patched = {
          src = inputs.zen-browser;
          patches = [ ../../patches/zen-browser/fix.patch ];
        };
      }
    '';
    type = lib.types.attrsOf (lib.types.submodule patchedInputModule);
  };

  imports = [
    (lib.inputMetaModules [
      (lib.mkAliasOptionModule [ "patch" ] [ "meta" "patch" ])
      ({ config, ... }: {
        options.meta = lib.mkOption {
          type = lib.types.submodule {
            options.patch = lib.mkOption {
              type = lib.types.submoduleWith {

                shorthandOnlyDefinesConfig = true;

                modules = [
                  patchedInputModule
                  {
                    config._module.args.name = lib.mkForce config._module.args.name;
                    config.hash = patchHashes.${config._module.args.name} or null;
                    config.src = realInputs.${config._module.args.name};
                    config.enable = lib.mkDefault false;
                  }
                ];
              };
            };
          };
        };

      })
    ])
  ];
  config = {
    #    flake-file.nixConfig.allowUnsupportedPlatform = true;
    patchedInputs =
      config.flake-file.inputsWithMeta
      |> lib.filterAttrs (_: v: v.meta.patch.enable)
      |> lib.mapAttrs (_: v: v.meta.patch);
    ff.flake-compat = {
      url = "github:nixos/flake-compat";
      flake = false;
    };
    flake.inputs = inputs;

    # Per-input overlay instead of `realInputs // buildPatched pkgs`. With `//`,
    # the patched value of EVERY re-evaluated input shares one attrset, and the
    # merge gives no syntactic hint that the rest are untouched. Building the
    # overlay with `mapAttrs` + a `patched.${name} or realInput` fallback keeps
    # evaluation lazy per input: reading an input not in `toBuild` (a non-flake,
    # or a flake that touches nothing patched) returns `realInputs` directly and
    # never forces `pkgs`, `applyPatches`, or the flake-compat re-eval — only the
    # names in `toBuild` enter the patch path. `buildPatched pkgs` stays a single
    # shared thunk, so re-evaluated inputs that reference each other still resolve
    # through the one `allInputs` fixpoint.
    #
    # Kept for anything reading `self.newInputs`, but flake.nix no longer uses
    # it: it calls ../../lib/patched-inputs.nix directly, which is what lets it
    # build the flake in ONE module-system pass instead of two. Lazy, so it
    # costs nothing unless something actually reads it.
    flake.newInputs = impl.newInputs;

    perSystem = { pkgs, ... }: {
      apps.patch-input = {
        type = "app";
        program = lib.getExe (patchInputScript pkgs);
      };

      # Regenerates ../../patched-inputs.nix from the live aspect declarations.
      # Run after adding/removing a patch or toggling `patch.enable`.
      apps.write-patched-inputs = {
        type = "app";
        program = lib.getExe (
          pkgs.writeShellApplication {
            name = "write-patched-inputs";
            runtimeInputs = [ pkgs.coreutils ];
            text = ''
              set -euo pipefail
              repo="$PWD"
              if [ ! -e "$repo/flake.nix" ]; then
              	echo "error: run from the flake root (no flake.nix in $repo)" >&2
              	exit 2
              fi
              cat > "$repo/patched-inputs.nix" <<'GENERATED'
${generatedPatchedInputs}
GENERATED
              echo "wrote $repo/patched-inputs.nix"
            '';
          }
        );
      };

      apps.update-patch-hashes = {
        type = "app";
        program = lib.getExe (updateHashesScript pkgs);
      };

      # `nix run .#update` — bump inputs, then refresh the patch hashes that
      # the bump just invalidated. Resolved and built *before* the lock moves,
      # so it still runs even though the flake won't evaluate in between.
      apps.update = {
        type = "app";
        program = lib.getExe (
          pkgs.writeShellApplication {
            name = "update";
            text = ''
              set -euo pipefail
              nix flake update "$@"
              PATCH_HASHES=ignore nix run --impure .#update-patch-hashes
            '';
          }
        );
      };

      # Building these fails `nix flake check` if a declared patch is stale
      # (it no longer applies) or a recorded `hash` is stale (hash mismatch).
      # Entries with no patches are skipped: `patchSource` hands those back
      # as the pristine source path, which is not a derivation to build.
      checks =
        lib.mapAttrs' (n: _: {
          name = "patched-input-${n}";
          value = (patchedDrvs pkgs).${n};
        }) (lib.filterAttrs (_: hasPatches) config.patchedInputs)
        // {
          # Guard `buildPatched`'s fixpoint: every re-evaluated input — patched or
          # merely auto-unified — must resolve its own inputs to the *patched*
          # versions of them, not the pristine ones. E.g. `agenix` declares
          # `darwin` and `home-manager`, both patched, so severing the fixpoint
          # shows up here rather than as a mysteriously unpatched module at
          # rebuild time. Covers the whole `toBuild` set, not just declared patches.
          # The generated ../../patched-inputs.nix is what flake.nix reads to
          # build the patched inputs without running the module system. If it
          # drifts from what the aspects actually declare, flake.nix would
          # apply the wrong patch set — silently, since nothing else compares
          # them. Fail here instead. Refresh with
          # `nix run .#write-patched-inputs`.
          patched-inputs-generated-current =
            let
              generated = lib.mapAttrs (_: v: map toString (v.patches or [ ])) (
                import ../../patched-inputs.nix
              );
              live = lib.mapAttrs (_: v: map toString v.patches) (
                lib.filterAttrs (_: v: v.isInput) config.patchedInputs
              );
              missing = lib.attrNames (removeAttrs live (lib.attrNames generated));
              extra = lib.attrNames (removeAttrs generated (lib.attrNames live));
              changed = lib.filter (n: (generated.${n} or null) != live.${n}) (
                lib.attrNames (builtins.intersectAttrs generated live)
              );
            in
            assert lib.assertMsg (missing == [ ] && extra == [ ] && changed == [ ]) ''
              ./patched-inputs.nix is out of date — run `nix run .#write-patched-inputs`.
                missing from the generated file: ${lib.concatStringsSep ", " missing}
                no longer declared by aspects:   ${lib.concatStringsSep ", " extra}
                different patch list:            ${lib.concatStringsSep ", " changed}
            '';
            pkgs.emptyFile;

          patched-inputs-intertwined =
            let
              patched = toBuild;
              mismatches = lib.concatMap (
                name:
                let
                  deps = lib.filter (d: lib.elem d patched) (lib.attrNames (inputs.${name}.inputs or { }));
                in
                lib.forEach (lib.filter (d: inputs.${name}.inputs.${d}.outPath != inputs.${d}.outPath) deps) (
                  d: "  ${name} sees ${d} = ${inputs.${name}.inputs.${d}.outPath}, want ${inputs.${d}.outPath}"
                )
              ) patched;
            in
            assert lib.assertMsg (mismatches == [ ]) ''
              patched inputs are not intertwined — a re-evaluated flake is seeing an
              unpatched dependency:
              ${lib.concatStringsSep "\n" mismatches}
            '';
            pkgs.emptyFile;
        };
    };
  };
}
