# This file is generated by `nix run .#write-flake`. To make changes, edit the
# `ff.*` declarations in the aspects listed under `nixos` in ../../partition-map.nix.
#
# It exists only to hold inputs and their lock: the root flake reads
# `.inputs` out of it (see aspects/framework/partitions.nix) and never calls
# `outputs`. `nixpkgs` and every shared `follows` target are pinned to the
# root flake's locked rev so the two locks cannot drift; each is dropped
# again before the inputs are merged into the partition, and is here purely
# so the inputs below can `follows` it -- a `follows` cannot reach the
# parent flake.
{
  outputs = _: { };

  inputs = {
    arion.url = "github:hercules-ci/arion";
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    disko-zfs = {
      url = "github:numtide/disko-zfs";
      inputs = {
        disko.follows = "disko";
        flake-parts.follows = "flake-parts";
        nixpkgs.follows = "nixpkgs";
      };
    };
    flake-parts.url = "github:hercules-ci/flake-parts/f16b25b8c3d2809b87925d0b76652d7821a75c68";
    home-manager.url = "github:nix-community/home-manager/b8350fcdf54ccf553e46408053b1ac5b7038c18b";
    impermanence.url = "github:nix-community/impermanence";
    lanzaboote = {
      url = "github:nix-community/lanzaboote/v1.1.0";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-cachyos-kernel.url = "github:xddxdd/nix-cachyos-kernel/release";
    nix-flatpak.url = "github:gmodena/nix-flatpak/";
    nixos-hardware = {
      url = "github:NixOS/nixos-hardware";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nixos-images = {
      url = "github:nvmd/nixos-images/sdimage-installer";
      inputs = {
        nixos-stable.follows = "nixpkgs-nvmd";
        nixos-unstable.follows = "nixpkgs-nvmd";
      };
    };
    nixos-mailserver.url = "gitlab:simple-nixos-mailserver/nixos-mailserver";
    nixos-raspberrypi = {
      url = "github:nvmd/nixos-raspberrypi/main";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nixos-wsl.url = "github:nix-community/NixOS-WSL/main";
    nixpkgs.url = "github:nixos/nixpkgs/e8be7818e19ada32105a8af937a6a473b38167ca";
    nixpkgs-nvmd.url = "github:nvmd/nixpkgs/modules-with-keys-25.11";
    nixvirt = {
      url = "https://flakehub.com/f/AshleyYakeley/NixVirt/*.tar.gz";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    plasma-manager = {
      url = "github:nix-community/plasma-manager";
      inputs = {
        home-manager.follows = "home-manager";
        nixpkgs.follows = "nixpkgs";
      };
    };
    searchix = {
      url = "git+https://git.sr.ht/~alanpearce/searchix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
}
