# GENERATED by `nix run .#write-patched-inputs` -- do not edit by hand.
#
# SRI hashes of the patched trees for the `nixos` partition, built from
# the revs ./flake.lock pins here rather than the ones the root pins. The
# patch LISTS live in ../../patched-inputs.nix; only the hashes differ per
# partition. A missing entry just means "build it locally".
{

  home-manager.hash = "sha256-Cn9eILapIdq5/dWGpaCkl7Ljn9G2cpP0h9GPsLeIs2w=";
}
