{
  inputs,
  lib,
  den,
  config,
  ...
}:
{
  systems = [
    "x86_64-linux"
    "aarch64-darwin"
  ];
  imports = [
    inputs.flake-file.flakeModules.default
    inputs.flake-file.flakeModules.allfollow
    (lib.mkAliasOptionModule [ "ff" ] [ "flake-file" "inputs" ])
  ];
  den = {
    classes.inputs = { };
    schema.flake-mod = { };
    policies.inputs-to-flake-parts = _: [
      (den.lib.policy.route {
        fromClass = "flake-file";
        intoClass = "flake-mod";
        collectSubtree = true;
        path = [
          "flake-file"
        ];
        adaptArgs = lib.id;
        #      adaptArgs = { config, ... }: config.allModuleArgs;
      })
    ];
    policies.flake-parts-to-host =
      _:
      map (host: den.lib.policy.resolve.to "host" { inherit host; }) (
        builtins.concatMap builtins.attrValues (builtins.attrValues den.hosts)
      );
    schema.flake-mod.includes = [
      den.policies.inputs-to-flake-parts
      den.policies.flake-parts-to-host
    ];
    schema.host.include = [ den.policies.inputs-to-flake-parts ];
  };
  flake.den = den;

  #  disabledModules = [ (inputs.flake-file + "/modules/flake-parts.nix") ];

  #perSystem =
  #  { pkgs, ... }:
  #  {
  #    apps =
  #      config.flake-file.apps
  #      |> lib.mapAttrs (
  #        _: f:
  #        let
  #          pkg = f pkgs;
  #        in
  #        {
  #          type = "app";
  #          program = lib.getExe pkg;
  #        }
  #      );

  #    checks.check-flake-file = config.flake-file.check-flake-file pkgs;
  #  };

  flake-file = {
    #  prune-lock.enable = true;
    inputs.flake-file.url = "github:denful/flake-file";
    inputs.rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    do-not-edit = ''
      #                                _
      #  __ _ _   _ ___  ___ _   _| |__   ___ _ __
      # / _` | | | / __|/ __| | | | '_ \ / _ \ '__|
      #| (_| | |_| \__ \ (__| |_| | |_) |  __/ |
      # \__,_|\__,_|___/\___|\__, |_.__/ \___|_|
      #                      |___/
                  #          This file is generated by the `write-flake` script. To make changes, edit the source files in `aspects/modules/` and run `nix run .#write-flake`.'';
    outputs = /* nix */ ''
      inputs:
      inputs.flake-parts.lib.mkFlake { inherit inputs; } {
        # Import all *.nix files in the ./aspects directory
        # Except ones that start with '_'
        imports =
          with inputs.nixpkgs.lib;
          ./aspects
          |> fileset.fileFilter (file: file.hasExt "nix" && !hasPrefix "_" file.name)
          |> fileset.toList;

        _module.args.rootPath = ./.;
      }
    '';

  };

}
