# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{

  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot/efi";
  boot.loader.grub = {
    useOSProber = true;
    efiSupport = true;
    version = 2;
    device = "nodev";
    extraConfig = " set theme=($drive2)${pkgs.breeze-grub}/grub/themes/breeze/theme.txt";
    #    splashImage  ="/usr/share/grub/themes/breeze/background.png";
    #    splashImage = null;
    gfxmodeEfi = "1920x1080";
  };

}
