{
  inputs,
  lib,
  den,
  config,
  ...
}:
{
  systems = [
    "x86_64-linux"
    "aarch64-darwin"
  ];
  imports = [
    inputs.flake-file.flakeModules.default
    (lib.mkAliasOptionModule [ "ff" ] [ "flake-file" "inputs" ])
  ];
  den = {
    classes.inputs = { };
    schema.flake-mod = { };
    policies.inputs-to-flake-parts = _: [
      (den.lib.policy.route {
        fromClass = "flake-file";
        intoClass = "flake-mod";
        collectSubtree = true;
        path = [
          "flake-file"
        ];
        adaptArgs = lib.id;
        #      adaptArgs = { config, ... }: config.allModuleArgs;
      })
    ];
    policies.sources-to-flake-parts = _: [
      (den.lib.policy.route {
        fromClass = "nvfetcher";
        intoClass = "flake-mod";
        collectSubtree = true;
        path = [
        ];
        adaptArgs = lib.id;
      })
    ];
    policies.flake-parts-to-host =
      _:
      map (host: den.lib.policy.resolve.to "host" { inherit host; }) (
        builtins.concatMap builtins.attrValues (builtins.attrValues den.hosts)
      );
    schema.flake-mod.includes = [
      den.policies.inputs-to-flake-parts
      den.policies.sources-to-flake-parts
      den.policies.flake-parts-to-host
    ];

    schema.host.include = [ den.policies.inputs-to-flake-parts ];
  };
  flake.den = den;

  #  disabledModules = [ (inputs.flake-file + "/modules/flake-parts.nix") ];

  #perSystem =
  #  { pkgs, ... }:
  #  {
  #    apps =
  #      config.flake-file.apps
  #      |> lib.mapAttrs (
  #        _: f:
  #        let
  #          pkg = f pkgs;
  #        in
  #        {
  #          type = "app";
  #          program = lib.getExe pkg;
  #        }
  #      );

  #    checks.check-flake-file = config.flake-file.check-flake-file pkgs;
  #  };

  flake-file = {
    #  prune-lock.enable = true;
    inputs.flake-file.url = "github:denful/flake-file";
    inputs.rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    #    preProcess =
    #      serialized:
    #      let
    #        isFlake = name: ((serialized.${name}.flake or true) != false);
    #        autoFollow =
    #          name:
    #          let
    #            top = lib.attrNames serialized;
    #            sub = lib.attrNames (inputs.${name}.inputs or { });
    #            shared = lib.filter (n: n != name && isFlake n) (lib.intersectLists top sub);
    #          in
    #          lib.genAttrs shared (s: {
    #            follows = s;
    #          });
    #      in
    #      lib.mapAttrs (
    #        name: spec:
    #        if !(isFlake name) then
    #          spec
    #        else
    #          spec
    #          // {
    #            inputs = lib.recursiveUpdate (autoFollow name) (spec.inputs or { });
    #          }
    #      ) serialized;
    do-not-edit = ''
      #                                _
      #  __ _ _   _ ___  ___ _   _| |__   ___ _ __
      # / _` | | | / __|/ __| | | | '_ \ / _ \ '__|
      #| (_| | |_| \__ \ (__| |_| | |_) |  __/ |
      # \__,_|\__,_|___/\___|\__, |_.__/ \___|_|
      #                      |___/
                  #          This file is generated by the `write-flake` script. To make changes, edit the source files in `aspects/modules/` and run `nix run .#write-flake`.'';
    outputs = /* nix */ ''
      inputs:
      let
        lib = inputs.nixpkgs.lib.extend (import ./lib);

        # The patched `inputs`, computed WITHOUT running the flake-parts module
        # system. This used to be `(inputsFn inputs).newInputs`, i.e. a complete
        # mkFlake over all of ./aspects purely to learn which inputs to patch —
        # after which the whole thing ran a SECOND time with the result. The two
        # passes are separate module fixpoints, so Nix shared nothing between
        # them and every aspect was evaluated twice.
        #
        # ./patched-inputs.nix is generated (`nix run .#write-patched-inputs`)
        # and holds the only part that genuinely needs the module system: which
        # inputs are patched, and with which patches. Everything else is derived
        # purely here. `checks.patched-inputs-generated-current` fails if it goes
        # stale.
        patchedInputs =
          (import ./lib/patched-inputs.nix {
            inherit inputs lib;
            rootPath = ./.;
            patchSpecs = import ./patched-inputs.nix;
          }).newInputs;

        # All *.nix under ./aspects (except ones starting with '_'), split into
        # the base import list and one list per flake-parts partition. Anything
        # claimed by ./partition-map.nix is deliberately NOT imported here: that
        # is what keeps its `ff.*` inputs out of this file and out of flake.lock.
        # See aspects/framework/partitions.nix.
        aspectPartitions = lib.aspectPartitions {
          dir = ./aspects;
          map = (import ./partition-map.nix).buckets;
        };
      in
      inputs.flake-parts.lib.mkFlake
        {
          inputs = patchedInputs;
          specialArgs = {
            realInputs = inputs;
            inherit lib;
          };
        }
        {
          imports = aspectPartitions.base;

          _module.args.rootPath = ./.;
          _module.args.aspectPartitions = aspectPartitions // {
          inherit ((import ./partition-map.nix)) stubs;
        };
        }
    '';
  };
}
