{
  inputs,
  realInputs,
  lib,
  config,
  rootPath,
  aspectPartitions,
  ...
}:
# flake-parts partitions: keep inputs that only serve a subset of the flake's
# outputs out of the root flake.nix (and therefore out of flake.lock).
#
# Nix already fetches an input lazily -- `nixosConfigurations.secondpc` evaluates
# fine with `--override-input homebrew-core path:/var/empty`, so a rebuild never
# fetches it. What is NOT lazy is the lock: every input in flake.nix is a node in
# flake.lock, and `nix flake update`, `nix flake archive`, CI and any downstream
# consumer walk all of them. A partition is the only way to move an input out of
# the root lock while still being able to use it.
#
# A partition is a SUPERSET re-evaluation: `partitions.<p>.module` is
# `extendModules` over the entire top-level module set, plus that partition's
# aspects, with `inputs = rootInputs // extraInputs`. So base keeps defining
# everything, and a partition only adds -- which is why host-iterating aspects
# (deploy.nodes, ciMatrix, the rekey app) do not need to move: at base they see
# no extra aspects and evaluate to whatever they evaluate to, and every attribute
# that actually matters is read from `all` via `partitionedAttrs`.
let
  buckets = builtins.attrNames aspectPartitions.parts;

  # `extraInputsFlake` would let a sub-flake's `nixpkgs` win over ours inside the
  # partition (flake-parts merges `inputs // extraInputs`), so load the sub-flake
  # ourselves and drop it. The sub-flake declares `nixpkgs` only so its own inputs
  # can `follows` it -- a `follows` cannot reach the parent flake -- and it is
  # pinned to the root flake's locked rev by the generator below.
  subInputs =
    bucket:
    builtins.removeAttrs
      (import inputs.flake-compat {
        src = rootPath + "/partitions/${bucket}";
        system = throw "flake-compat is loading a partition in pure mode; `system` must not be forced";
      }).outputs.inputs
      [
        "nixpkgs"
        "self"
      ];

  # The base evaluation's input names. Subtracted inside each partition so the
  # generated partitions/<bucket>/flake.nix holds only that bucket's own inputs
  # (a partition's flake-file sees base + bucket, being a superset eval).
  baseInputNames = builtins.attrNames config.flake-file.inputs;

  # This aspect is re-imported inside every partition (superset eval), so a
  # partition declares partitions of its own. Those are never read -- but the
  # write-flake hook below is part of every evaluation, and letting a partition
  # keep it would make the hook's text reference its own nested output: infinite
  # recursion the moment the app is built. Nothing else about the nested
  # partitions is ever forced, so dropping the hook is the whole guard. (Testing
  # `partitionStack` instead would not work: reading a module argument to decide
  # what a module defines is itself an infinite recursion.)
  noNestedHooks.flake-file.write-hooks = lib.mkForce [ ];

  # Every partition also writes its own flake.nix, from the same `ff.*`
  # declarations that live next to the aspects using them.
  subFlakeModule = bucket: {
    imports = aspectPartitions.parts.${bucket} ++ [ noNestedHooks ];
    flake-file = {
      intoPath = "partitions/${bucket}";
      # mkForce: a partition re-imports aspects/framework/flake-file.nix (and
      # aspects/base/caches.nix), which define these for the ROOT flake.nix.
      # Nothing ever evaluates a sub-flake's outputs or honours its nixConfig.
      outputs = lib.mkForce "_: { }";
      nixConfig = lib.mkForce { };
      do-not-edit = lib.mkForce ''
        # This file is generated by `nix run .#write-flake`. To make changes, edit the
        # `ff.*` declarations in the aspects listed under `${bucket}` in ../../partition-map.nix.
        #
        # It exists only to hold inputs and their lock: the root flake reads
        # `.inputs` out of it (see aspects/framework/partitions.nix) and never calls
        # `outputs`. `nixpkgs` is pinned to the root flake's locked rev so the two locks
        # cannot drift; it is dropped again before the inputs are merged into the
        # partition, and is here purely so the inputs below can `follows` it -- a
        # `follows` cannot reach the parent flake.
      '';
      preProcess =
        serialized:
        {
          nixpkgs.url = "github:nixos/nixpkgs/${realInputs.nixpkgs.rev}";
        }
        // builtins.removeAttrs serialized baseInputNames;
    };
  };

  partitionedInputs = lib.mergeAttrsList (builtins.map subInputs buckets);

  # `all` is base + every partitioned aspect: the evaluation that can see the
  # whole tree, and therefore the one every cross-cutting output is taken from.
  # It writes no flake.nix of its own -- each bucket already owns one.
  allPartition = {
    extraInputs = partitionedInputs;
    module = {
      imports = aspectPartitions.all ++ [ noNestedHooks ];
      # `checks` is taken from this partition, and that includes flake-file's
      # own check-flake-file, which diffs the committed root flake.nix against a
      # freshly generated one. Here the aspect tree also carries the partitioned
      # `ff.*` declarations, so subtract them back out or the check reports every
      # partitioned input as missing from the root flake.
      flake-file.preProcess =
        serialized: builtins.removeAttrs serialized (builtins.attrNames partitionedInputs);
    };
  };
in
{
  imports = [ inputs.flake-parts.flakeModules.partitions ];

  ff.flake-compat = {
    url = "github:nixos/flake-compat";
    flake = false;
  };

  partitions =
    lib.genAttrs buckets (bucket: {
      extraInputs = subInputs bucket;
      module = subFlakeModule bucket;
    })
    // {
      all = allPartition;
    };

  # Which flake outputs come from `all` instead of the base evaluation. Keep this
  # list to attributes that are genuinely dev-time or need the whole host set:
  # every entry here is another full den pipeline run when it is evaluated.
  #
  # `packages` deliberately stays at base -- `packages.write-flake` regenerates
  # the root flake.nix from `config.flake-file.inputs`, and taking it from the
  # superset partition would write the partitioned inputs straight back in.
  partitionedAttrs = {
    apps = "all";
    checks = "all";
    ciMatrix = "all";
    darwinConfigurations = "darwin";
    deploy = "all";
  };

  # `nix flake update` only touches the root lock, so bring the partitions along:
  # regenerate their flake.nix (the `nixpkgs` pin tracks the root's new locked
  # rev) and re-lock each one. Re-entering through `nix run` rather than a baked
  # derivation is deliberate -- this hook was built from the pre-update
  # evaluation, so the pin it would write is the old one.
  perSystem = {
    update-hooks.postFlake.update-partition-flakes = ''
      nix run .#write-flake
      ${lib.concatMapStringsSep "\n" (bucket: "nix flake update --flake ./partitions/${bucket}") buckets}
    '';
  };

  # `.#write-flake` writes the root flake.nix, then this hook writes each
  # partition's. Reading a partition's flake-file forces that partition's
  # evaluation, which is why this is a hook on the app rather than something the
  # base evaluation does unconditionally.
  flake-file.write-hooks = [
    {
      index = 20;
      program =
        pkgs:
        pkgs.writeShellApplication {
          name = "write-partition-flakes";
          meta.description = "Generate partitions/*/flake.nix";
          text = lib.concatMapStringsSep "\n" (
            bucket: lib.getExe (config.partitions.${bucket}.module.flake-file.apps.write-flake pkgs)
          ) buckets;
        };
    }
  ];
}
