# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "nomodeset" ];
  fileSystems = {
  "/" =
    { device = "/dev/disk/by-uuid/5737721a-ff87-400e-b32e-0988e4781e7c";
      fsType = "ext4";
    };

  "/home" =
    { device = "/dev/disk/by-uuid/d5e8c31c-eebf-4907-a8ce-309e2ba575aa";
      fsType = "ext2";
    };

  "/boot/efi" =
    { device = "/dev/disk/by-uuid/4AD0-8E16";
      fsType = "vfat";
    };
  "/mnt/hdd" = 
    { device = "/dev/sda2";
      fsType = "ntfs";
    };
   };
  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
