format = """$username$hostname$status$directory$shell$rust$package$cmd_duration$git_status$nix_shell$haskell$purescript$python$julia$lua$golang$docker_context$package$fennel
$character"""

scan_timeout = 10

[shell]
disabled = false
powershell_indicator = "[pwsh](blue)"
zsh_indicator = "[zsh](#8BB2C1)"

[character]
success_symbol = "[λ](bold 195)"
error_symbol = "[λ](bold white)"

[hostname]
format = "[$hostname](bold green) "
ssh_only = true



[username]
style_user = "white"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = false


# Wait 10 milliseconds for starship to check files under the current directory.


# Don't print a new line at the start of the prompt

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "


[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = "❄️ "
impure_msg = "[impure](bold red)"
pure_msg = "[pure](bold green)"
format = 'via [$symbol$state( \($name\))](bold blue) '

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
