{
  lib,
  buildNpmPackage,
  importNpmLock,
  nodejs,
  fetchurl,
  fetchFromGitHub,
}:
# Microsoft 365 (Outlook mail + calendar, over Microsoft Graph) MCP server.
#
# Packaged from the *published npm tarball* rather than the git tag, which is
# unusual here and deliberate: the server's Graph client is code-generated by
# `npm run generate`, which downloads Microsoft's OpenAPI spec at build time.
# `src/generated/client.ts` is gitignored upstream, so a build from the tag emits a
# `dist/` with no `dist/generated/client.js` -- tsup reports success and the binary
# dies at startup with ERR_MODULE_NOT_FOUND. The npm tarball ships that generated
# module already built, so we take `dist/` as-is and never run the build.
#
# The tarball has no lockfile, so dependencies still come from the git tag's
# `package-lock.json`, copied in below. Packaged at all (rather than run as
# `npx -y @softeria/ms-365-mcp-server`) because ZeroClaw spawns its stdio servers
# from a launchd agent, whose PATH does not contain the nix profile's `npx`.
let
  # Fetched only for `package-lock.json`; none of its sources are compiled.
  lockSrc = fetchFromGitHub {
    owner = "softeria";
    repo = "ms-365-mcp-server";
    rev = "v0.145.1";
    hash = "sha256-mMQ4nB9/qLfWHQGdRHxsXfigXPC0t5KnFB1FFUl5VAk=";
  };
in
buildNpmPackage (finalAttrs: {
  pname = "ms-365-mcp-server";
  # Upstream's checked-in package.json says `0.0.0-development` -- semantic-release
  # rewrites it at publish -- so the git tag is the only honest version source, and
  # the lockfile it ships carries the placeholder (patched to match below).
  version = "0.145.1";

  src = fetchurl {
    url = "https://registry.npmjs.org/@softeria/ms-365-mcp-server/-/ms-365-mcp-server-${finalAttrs.version}.tgz";
    hash = "sha256-HXBbZ82B4d6woJ8rSIlhcBv4ijM/vo0KH1BXiupy1d4=";
  };

  postPatch = ''
    cp ${lockSrc}/package-lock.json .
    chmod +w package-lock.json
    # `npm ci` refuses to run when the lockfile's root version disagrees with
    # package.json's, and the two disagree by construction (see above).
    substituteInPlace package-lock.json \
      --replace-fail '"version": "0.0.0-development"' '"version": "${finalAttrs.version}"'
  '';

  npmDeps = importNpmLock { npmRoot = lockSrc; };
  npmConfigHook = importNpmLock.npmConfigHook;

  # `keytar` is an optionalDependency whose 7.9.0 node-gyp build no longer compiles
  # against a current clang (node-addon-api's `unknown_array_type` in-class
  # initializer is rejected as non-constant). Skipping install scripts leaves it
  # unbuilt, which the server handles by design: `await import('keytar')` throws, it
  # logs "keytar not available, using file-based credential storage", and the MSAL
  # cache plus its encryption key live wherever MS365_MCP_TOKEN_CACHE_PATH points.
  # That is the mode a launchd agent wants anyway -- a keychain read from a
  # background job is exactly the thing that fails at 3am.
  #
  # `--omit=optional` was the first attempt and is too coarse: esbuild ships its
  # per-platform binary as an optional dependency too.
  #
  # `--omit=dev` rides along because nothing here is compiled: the dev tree is
  # tsup/vitest/eslint, none of which the installed binary can reach.
  npmFlags = [
    "--ignore-scripts"
    "--omit=dev"
  ];

  # `dist/` comes prebuilt in the tarball; there is nothing to compile.
  dontNpmBuild = true;
  # npmInstallHook's `npm prune --omit=dev` re-resolves a dev-only script
  # dependency (`patch-package`) against the network. Nothing to prune anyway --
  # `--omit=dev` above means dev packages were never installed.
  dontNpmPrune = true;

  inherit nodejs;

  meta = {
    description = "Microsoft 365 / Outlook MCP server (mail, calendar, OneDrive, Excel) over Microsoft Graph";
    homepage = "https://github.com/softeria/ms-365-mcp-server";
    license = lib.licenses.mit;
    mainProgram = "ms-365-mcp-server";
  };
})
