# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "nvidia" "nvidia_modeset" "nvidia_uvm" "nvidia_drm" ];
  boot.kernelModules = [ "kvm-intel"];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "nvidia-drm.modeset=1" ];
  fileSystems = {
    "/" = {
      device = "/dev/nvme0n1p6";
      fsType = "ext4";
    };

    "/home" = {
      device = "/dev/nvme0n1p5";
      fsType = "ext2";
    };

    "/boot/efi" = {
      device = "/dev/nvme0n1p1";
      fsType = "vfat";
    };
    "/mnt/hdd" = {
      device = "/dev/sda2";
      fsType = "ntfs";
      options = [ "defaults" "uid=1000" "auto" "rw" ];
    };

  };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
