# GENERATED by `nix run .#write-flake` -- do not edit by hand.
#
# Holds this layer's inputs and their lock, nothing else. The root reads
# this lock as DATA (lib/inputs.nix) and never calls `outputs`.
#
# Entries with no `follows` of their own are CARRIED: a `follows` cannot
# cross a flake boundary, so a name this layer only refers to still has
# to be declared here, pinned to its owner's locked rev. At merge those
# resolve to whichever source OWNS the name -- root or another layer --
# so the node below exists but is never the value anything resolves.
{
  outputs = _: { };

  inputs = { homebrew-cask = { url = "github:homebrew/homebrew-cask";
flake = false; };
homebrew-core = { url = "github:homebrew/homebrew-core";
flake = false; };
homebrew-gcenx = { url = "github:gcenx/homebrew-wine";
flake = false; };
homebrew-speedtest = { url = "github:teamookla/homebrew-speedtest";
flake = false; };
homebrew-typewhisper = { url = "github:typewhisper/homebrew-tap";
flake = false; };
nix-homebrew = { url = "github:zhaofengli/nix-homebrew"; }; };
}

