#!/usr/bin/env lua

local home = os.getenv("HOME") or ""
local config_dir = os.getenv("CONFIG_DIR") or (home .. "/.config/sketchybar")
package.path = package.path
	.. ";" .. config_dir .. "/?.lua"
	.. ";" .. config_dir .. "/?/init.lua"

require("helpers")
require("init")
