# GENERATED by `nix run .#write-flake` -- do not edit by hand.
#
# Holds this layer's inputs and their lock, nothing else. The root reads
# this lock as DATA (lib/inputs.nix) and never calls `outputs`.
#
# Entries with no `follows` of their own are CARRIED: a `follows` cannot
# cross a flake boundary, so a name this layer only refers to still has
# to be declared here, pinned to its owner's locked rev. At merge those
# resolve to whichever source OWNS the name -- root or another layer --
# so the node below exists but is never the value anything resolves.
{
  outputs = _: { };

  inputs = {
    home-manager = {
      url = "path:../../lib/stub";
      flake = false;
    };
    nixpkgs = {
      url = "path:../../lib/stub";
      flake = false;
    };
    plasma-manager = {
      url = "github:nix-community/plasma-manager";
      inputs = {
        home-manager.follows = "home-manager";
        nixpkgs.follows = "nixpkgs";
      };
    };
  };
}
