name: "Check formatting & lints"

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]
    paths:
      - "Justfile"
      - "Cargo.toml"
      - "Cargo.lock"
      - "xtask/Cargo.toml"
      - "crates/**"
      - "xtask/src/**"
      - ".cargo/**"
      - ".github/workflows/check.yaml"
  push:
    branches-ignore:
      - "update-*"
    paths:
      - "Justfile"
      - "Cargo.toml"
      - "Cargo.lock"
      - "xtask/Cargo.toml"
      - "crates/**"
      - "xtask/src/**"
      - ".cargo/**"
      - ".github/workflows/check.yaml"

jobs:
  treewide-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checking Code (format, lints, etc.)
        run: |
          eval "$(nix print-dev-env)"
          just check || exit 1
