password: ENC[AES256_GCM,data:OJZziCeEkfS1mA==,iv:WH5bg5TTuzg+RVJsmwWHdZPG4y922Beycr1J+w0QmUI=,tag:e9rdC3nWVHQo56Y+HyrjIg==,type:str]
github_token: ENC[AES256_GCM,data:RAo+j/BrDgssvFbctbG+QBz1Vs2+p3F/RMvBmh1uzRsrTL8ccu45JGo0jRgdzryHlIKuw7UMROHVO/imnz2FGGTv4kJpRGi4kXTVLLE7rWzMu7lz7haRJJm1F94E,iv:GReqDl/yFt+b1/cHlwX5nIPWSL+m6rAyQ6X5r0xiY+8=,tag:YuyiVeFhjhDJVc4vE5JXcQ==,type:str]
samba:
    smb_password: ENC[AES256_GCM,data:SBKvJVXQoaGxdVf50uRU,iv:KJagJzkuxX6FZO9IMAUeny/8slPUKUUYgJF9QRhhbR0=,tag:bmaiiBYAOBXFCMNSIl/vIg==,type:str]
    smb_username: ENC[AES256_GCM,data:ZQdu,iv:rJzv/1ovgzripHlRwuFuVeYxGObC6s54AhEWEmUM6IQ=,tag:ZnlYV7t7HhDZjNEu6hY0+Q==,type:str]
mopidy:
    listenbrainz_token: ENC[AES256_GCM,data:b6ssKb+pgNu9GieJ5wVDoidyS/JG85wrYOcRyudevWiXe5cm,iv:1x0LI8rhTUinoIpxOwqegVo2ivSMgtuhpriExXDHyQ8=,tag:YNehleQNEeXV/DOAzhhEUw==,type:str]
cachix_auth_token: ENC[AES256_GCM,data:8HS8Vtjcw+sa7czBs0hkgwJaWAGlpQuyh5NhFbHZFnXYAC2sv+9UdniK/HWaCNE+3ix+J4q+kLZqFoM2iBdSi3MW4JBXK2oYuiMKLIuhxRVnpMuYNi9eYSM1Yk/6YDCywADmT5ZX2fRTyFKC80vZtn9Lm72ByppUgC4roXM60JYV9p7uSWNbQx17alyOTTOEBzll6i0=,iv:HilLh8gqXDkk9H9+61PwHplKVk/c7KrFI4+3RWK/aR8=,tag:EsfS/TTHCd22G5/QZqmYgw==,type:str]
pia:
    pia_private_key: ENC[AES256_GCM,data:8H8oqtJePhmCQcp5UbbSDbgMNoWICFh58F+5RL7n4YjpNrETvavNUy0VvgI=,iv:lyfI3nvK9p+n+u+r96C31QB+94AHl3bRjMHct8rSjbM=,tag:I1bXB52YAVDxWEy9c7rdWg==,type:str]
wakatime_config: ENC[AES256_GCM,data:zUrRNUo6CO6vyKUaV+IrvXyB5d0AAz1wlOECZsqw6AxwZna5p8OyTHhc/mdU6IsZFP9yrQmMlG3nRXEf3SCc,iv:lgh5D52r4rH9gYxCnHMhMn/kOlaFJLAQTkuDjkkLLS0=,tag:OOgnLMFxF6o1yGkrmvr6bw==,type:str]
sops:
    age:
        - recipient: age1wl25zsmys6cdzacrx4xh2fe89jk8enx4dalc52075kg9rdnuxf9qe2yw7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVlJiZWRjUjhOOG9Zci8y
            MllNQ253dEFzTGxQRytsODM2TElWQ1M1bkNNCjIrOU9acXhrMmVYS0FhRlBnUGd1
            dWpycGpweHMvZVlhM0xiNFFzVlg0WEEKLS0tIHZqdGUwajlPazg4THhJbnBweXg5
            K1BaK2ZMSUJ2V3ZuMmJvU1VnVUJpdmsK8jN75/qCWLP89Ie7v0zl5pNeMl1ngRTb
            BvDLt96sLoVLoZSE9UWLu5NlYefkpY+9SJ1pbxRwKr2Z7jH0FbZNmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j96shgsvmwp4ltf6evxrxf5tp883tveqxx6knpxfm5n9gc2tr4qs6phnu6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMFpDTHZOVzQxTTlCaWZ5
            VEZFTS9FQlIxb2lqR25zQ09GMDJTMzlob0U0CmRVNHJLaUZJT3hrUTlrYkc4cVBT
            NitNRTlxQ0tBWXVZcTdvMDZpRzFnRjAKLS0tIFFpU0NzNDQvbWhLVDF0d212MVAz
            WWFBd0NQSE44ZHR3QTM3U3RYMTdlWnMKxZo9vF4vorWpY0kNVawAQMDpZGnYDnTm
            J26YxGSMafF0Ghadz9XomYcYaq9qZF5HHmHYd+Ysokcx4/97EMgMKQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dkwz3c2jprv8kz9e4r2yj5ugfsgx8hvmxc466k96d38c9hnuxp0s2u4qpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ2haWlU2UXYrQkpnNGVO
            NU5Tc08rUDhxNWNoSnFQamRDZUlvejlqOWlZCklseHprWklPd2VTR1JoTzlwb2Zs
            clRoL0dhaVJXUkhnNXZ0bWVEVDZWSHcKLS0tIFRHVnBMNjZtU29pc2ZIU2VDSTBy
            RVRtWW5GV0x2SVZVL0hYcTlrcGMxR1UKLJ4QoPtLLH+GboWSFJ4O2QDna7mWIorD
            DXv3dX2FF3pPJCYmIa45hLGUb/y0KYH5+UJMQaKYEP5QEe4bYLUlnQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yuapchjs3ucvhftlv75t26m5vfyjdjjtrpmknvnk7cdy9n7jmf5sgvht94
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaHR4cDVtL1dBSXRIU09q
            WHNlM0o5cGdOK1cxMkNPaGljL2dQK0dRaUQwCjVYYlBJak43cGg3Q2YyMmo5WWE2
            eS9WL1pscW9oUm1sV296Rk1hL0xNOEEKLS0tIHVNRVYvSDN1T2JxUjFCa3hmb095
            Tnhhc0JFd2w1NHU5dDNPd1Irb2xMSEkKYdq8Qxr2hrJhYtWvMWrNSovAV19YHLXI
            a6ucM6C1JDm5tlc4lEx7y9IRwT2pqDKYqlEgpJOjJp1WoaQvsgLKtA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ga2d9jh6wkrhqejfl4e4wdt88429ec8w0ek3r5lhlkf9c66vy4esw8jznm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bU5wTUN4MmFJNjl5SlBu
            d3EvNDZKeUQ4Umh3SkxDejNoNDlQQkp6K2trCmpzbStsaEUzdjBndGVETEl1bGJD
            Z1ZqSk54SndJRXlhNk92bFcyMm9ENXMKLS0tIDl4aVBjLzg4T1FoZEh0SUt2MGlI
            NVNKcEgweVFkRUpSUDQyd2NBZ0JZb1EKurzZnl+8lJshPIkD9SjNvzLZ3//HbUS2
            M9dEVKAdm9Flc0LG1KpCaCFUcoIRpM6sdIQ0HCaafQ020mGmxZJtZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n6ufle4xhy0fe6nkwp7yzfv7mxqdm06wtp2uj0dwzrtfv4rtzpfsmslgjn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZ1l1UTAwY3RMVHpwekZ5
            V0swbk1rWTlIa3JXS0FBNnMzdUlhdU1laDNBCnB3cmJsZDIxdjUyQjhoTEVqb1Q1
            d2lOaFQ5WWhBR3JkLzhuVHFObTMxNmcKLS0tIDBsd0FzaHNkQ2NlY0swbzh0Z0hH
            cWF2UnRRSjcwVk5pVFcrN25sNFlCdlUKKNPLX5DsunkwLbN8BDe1PZ7c9pEqttNg
            K1WphmM8rLYu96ZzZQFfyuSy/bXGJm/RFrEM2R6tBFtc/NwhzqEpSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T07:56:00Z"
    mac: ENC[AES256_GCM,data:5qLUuxaEiKTOS4aCSAvDtpr40TsIdN+mK3n1ElS4rzFSCp74tlcTPs36ZXGD5/dJH1kr1tUuzHBCAxG3yQH3hEogodsdcZX928QYnXoo4NCY3+YSYPbT1irT+WN56NnUOr9VkABY+Stb6i6nyYE24BB6Hl9RSHQ5wCwCuA+Ebi8=,iv:JY8WffWQKECcD6x+Mn0wu9by//BEGISDLWIRA1um25Y=,tag:giZ0gTp/yEN++H0D6T/Wag==,type:str]
    pgp:
        - created_at: "2025-12-30T05:18:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DMrkGuet0+uQSAQdAXP+oxGriKt3X2lGT/y+EO0+aAcJgAk42IwU9PGZl6W4w
            K6hDKrUnRD24z+TFYcIxWp8cAfDCai85joWtOOFftyJNSpnoHWkZsRm+WhMXPAwX
            0l4Bfo9kCyzcz7Cn+6FECwdRjTSZhoMcou69/PuPC9FPuKdZ2QVNQmm8Emp1sfqs
            FpSMg9gYLVHS5xpcW+mNNJ78QitCflw95MSPgjnkJYCJ4uXvZUYfy/NiHJS9rPw/
            =NWVs
            -----END PGP MESSAGE-----
          fp: B0BF08E64E9D0F45DAC341F0725B4C10D3322170
    unencrypted_suffix: _unencrypted
    version: 3.11.0
