password: ENC[AES256_GCM,data:OJZziCeEkfS1mA==,iv:WH5bg5TTuzg+RVJsmwWHdZPG4y922Beycr1J+w0QmUI=,tag:e9rdC3nWVHQo56Y+HyrjIg==,type:str]
github_token: ENC[AES256_GCM,data:OcqDt+dqpjFVlrWmP5HDiIqjwp5rDBAbh5OjcEJ1jxkaT9p7kjgEB2WHS/mbOORIy5muJjhk87LoSZgHss6J4c2cm1oj+1c02k0OcrzrTlTFZt7Nnnfo/S9NtGMR,iv:Ma+fZ/CBSQ/5Q3OamWEjYs8isl5zO90G9R1WoXJtE0k=,tag:8chXvi7D1aDf2OpziPF7jQ==,type:str]
samba:
    smb_password: ENC[AES256_GCM,data:SBKvJVXQoaGxdVf50uRU,iv:KJagJzkuxX6FZO9IMAUeny/8slPUKUUYgJF9QRhhbR0=,tag:bmaiiBYAOBXFCMNSIl/vIg==,type:str]
    smb_username: ENC[AES256_GCM,data:ZQdu,iv:rJzv/1ovgzripHlRwuFuVeYxGObC6s54AhEWEmUM6IQ=,tag:ZnlYV7t7HhDZjNEu6hY0+Q==,type:str]
pia:
    pia_private_key: ENC[AES256_GCM,data:8H8oqtJePhmCQcp5UbbSDbgMNoWICFh58F+5RL7n4YjpNrETvavNUy0VvgI=,iv:lyfI3nvK9p+n+u+r96C31QB+94AHl3bRjMHct8rSjbM=,tag:I1bXB52YAVDxWEy9c7rdWg==,type:str]
sops:
    age:
        - recipient: age1wl25zsmys6cdzacrx4xh2fe89jk8enx4dalc52075kg9rdnuxf9qe2yw7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcUMzckdSaFJjU0lpTEVD
            aEVVZDJyTi95Z3NzTUM2d29LSUsvckhXS1dNClJ1dlJwSWdvaHdpWng3bmtRWWdW
            SVBLRHBJc3JwRk5lU3hYY2h6bzM0Z2MKLS0tIEJBd01XbURUaUo3cGprK2ptNHhK
            UGl1Wm9BK1p2YVZGcVVwZ1JOc3JXVmMKirf2zp8ysGNWiuSaslW4vhMInUQuxBmo
            OxEToyOzlHL32grG+JwiqDgJj3u1Me7I1VhlggtyFWH3oDvgPzZjRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dkwz3c2jprv8kz9e4r2yj5ugfsgx8hvmxc466k96d38c9hnuxp0s2u4qpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2pPMSs2WkM1Um9QNEx5
            SUFwUHB6TGhaYzVFK09JakpwbzRneENiUm40Ck10QmRRTFVueU1TRDFLNkw4V3dU
            WnJPNjZJVlZuMTVDYjlsSzVXODU0UUEKLS0tIGR0MG5JWlJOVmtUV0MxWUhYZ0FO
            blp2eXZTOENubGhLUVpvYm5vZTRITjgKZdGvBrhKsYsN8AxPEHCR2hHgRx4LaUS0
            05LrbPLr3mahG+lOx69r/kdLsCpS4j0oaGVIVQoqUhsgxWewBXKyrg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yuapchjs3ucvhftlv75t26m5vfyjdjjtrpmknvnk7cdy9n7jmf5sgvht94
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoakl2M3BrV1Q3a1UwZ3Za
            Rkswbkt1MlJTdzhnSnhES1FqRGg5Tnl2WDJZCkVhaWMvMytpSFJqWVV0Q2ZlbmJN
            bEFCeGlaTmoyUTczcEV0aXB5ZUFGVTgKLS0tIG96ZTVxN3NwY1dxSkZXeDlxYjc5
            dStPVlozLzZ4NDlldmNDK294bFBGZEEKQlK7UNJFXaPLgmRQ1Pg5rydj39syib0E
            NCNm5J8hebs1NV3U9uNXMBIJURCuun2dsNm9NFbMytGtLjGOGNyZQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ga2d9jh6wkrhqejfl4e4wdt88429ec8w0ek3r5lhlkf9c66vy4esw8jznm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWjFOVkJZVEpXWnBpTUha
            YWJrWEJMcFliK3VwUm43VkZaU3FybWRZbVM4CmxXakl4dTUzODhvRm04b29URFBU
            REhFYVFDb1hyRnljVXlQbWE3VkdhMm8KLS0tIDZ2YWFrTytMMWNQM1h0US9qY2tt
            YkVORUVBYnRxb2lIdVdSQUprSzRlblEKn18eLp5mYwc2ZOkZrPGRMenZ23pPnVr5
            v8MJZfsBvSYmWg/RK0qYXdD83GsV5NqMMmjwAiTbS0h6GJdDVUrsaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T07:48:40Z"
    mac: ENC[AES256_GCM,data:n7QE6xz/7gpNE7KmtwWy5Y+S1Ib61ZZ1v/cHVu2Q0k5YYCr/CsalhdFXetu7y32l9jExH9fOayOO5WEYn7LoVkJDZuQUXnlMnNgn22ufG9/WuueAtsx083GR/HYigfLGB/LKgAFTZcatGHVoEpWj2fvkheuF3pwHucN2uOt2Lgw=,iv:3P8sPMSA07xx9CANcAKlpd3HviLtWHSjobhe7y8Tk+Y=,tag:FpKd/r/1iVQv0ViGIDFrtA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
