password: ENC[AES256_GCM,data:OJZziCeEkfS1mA==,iv:WH5bg5TTuzg+RVJsmwWHdZPG4y922Beycr1J+w0QmUI=,tag:e9rdC3nWVHQo56Y+HyrjIg==,type:str]
github_token: ENC[AES256_GCM,data:BsgXqsPCI8b9jF0c4HQSiTmIXUXsp5FvG/mUYn+wdrk0AZXNyA+gywT3l3wyDVrEXlEn7Yyytc4LGUK5FP90k7YuQiUVnDcl4Eo+ldtrRjPR/NbGJGr0zl6isVko,iv:fMz8TwLYrF57kd07fje8pgk6Gd/+cdkl2837ja4ooq8=,tag:oawvUdEfbC672fI17i8P6w==,type:str]
samba:
    smb_password: ENC[AES256_GCM,data:SBKvJVXQoaGxdVf50uRU,iv:KJagJzkuxX6FZO9IMAUeny/8slPUKUUYgJF9QRhhbR0=,tag:bmaiiBYAOBXFCMNSIl/vIg==,type:str]
    smb_username: ENC[AES256_GCM,data:ZQdu,iv:rJzv/1ovgzripHlRwuFuVeYxGObC6s54AhEWEmUM6IQ=,tag:ZnlYV7t7HhDZjNEu6hY0+Q==,type:str]
mopidy:
    listenbrainz_token: ENC[AES256_GCM,data:b6ssKb+pgNu9GieJ5wVDoidyS/JG85wrYOcRyudevWiXe5cm,iv:1x0LI8rhTUinoIpxOwqegVo2ivSMgtuhpriExXDHyQ8=,tag:YNehleQNEeXV/DOAzhhEUw==,type:str]
pia:
    pia_private_key: ENC[AES256_GCM,data:8H8oqtJePhmCQcp5UbbSDbgMNoWICFh58F+5RL7n4YjpNrETvavNUy0VvgI=,iv:lyfI3nvK9p+n+u+r96C31QB+94AHl3bRjMHct8rSjbM=,tag:I1bXB52YAVDxWEy9c7rdWg==,type:str]
sops:
    age:
        - recipient: age1wl25zsmys6cdzacrx4xh2fe89jk8enx4dalc52075kg9rdnuxf9qe2yw7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUHBQckFrUnRXU2Fnbzd0
            SHpNZ2EwZHhDQURReFlYTjh5TXNrYVJBQXpNClFRalZQSWtmUkxCOC9zeHZhRmtr
            eDE1N1RsQ3czalVOTnhqd0RHdklDZEUKLS0tIEdIR1FLaWlaeDRBRytwbGhrdFlv
            MkdkTFhydVJlZUpMSmdGK3U1a01WL1EKP5s7ebfFmqU5fvQH043ndQ5pmotZHQEX
            mag8b5k6r7V80s/DNTHVeiCOTb9UL0NWhgBGsc8+cMSKKgJkPNWdpg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dkwz3c2jprv8kz9e4r2yj5ugfsgx8hvmxc466k96d38c9hnuxp0s2u4qpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SnVnMytUVzcrbFZ3ZzF3
            VGFCZ25tNUlPWU9DZUduUi83cCs5b2lUR1JBCjkyMzB4N1U4TmhsRGtGRkl2QTN4
            N1UyMzNiWkVGY1VyTWtYbVMvUW1rUmMKLS0tIDF1cVBtbVlZc3gyVFYyWDZPc1J3
            SlJTbVRXSW85T3c1U1owNGpOdUczakkKq/JOhEVKG4rkP2lk643IglvcfDFgitiM
            +JmLcfdnSJt0IPwtMZS8ID86HGQjFtRHE3wU4d7fvlKPEoseiqDQ+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yuapchjs3ucvhftlv75t26m5vfyjdjjtrpmknvnk7cdy9n7jmf5sgvht94
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNTl3azE4N01VNFFBMTVP
            aHRuRFNvNEs4QitnaExOUUNrRmtrendaWUhFCmlHaEJvUmdxcFFIWkMrUnRSN1FC
            bmdiWmxsSTdyMEdFdGUrUDNvbVhnTVkKLS0tIGlJc3liazJ4bElVS21tS0E3dVQv
            ek81aXZxeXhzSUJoMlM1SDNCZ3pqRnMKA+BdmsFpUkCeUr+HFplPon9JJNw6b5+I
            jI3nZYRk80QJqe7ukOKvy6r6FfSe5xCrhNo48vVNhvKRNvYylOdRcQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ga2d9jh6wkrhqejfl4e4wdt88429ec8w0ek3r5lhlkf9c66vy4esw8jznm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVDBPc0owcXhtdXMyNVdi
            aHd4QU1jWkIxM2pKbElUNERuekg4WlhXOG4wCkpLb24yVXdIV0ZRcDdsNWcvQzFI
            TEYvODFHMnFTZm1oVUMvSy9UVmVaWGsKLS0tIEFXaW85NGF6WFlwTjJLWldmQTd6
            ek93ZVc4eDBTL0FvN0VBcmFMajJHTjgKc1M5zBDgQ5HqVhMNNqyu8v38Uq+09it0
            1jvvmQOMqZIo5/ZHfIVYBwal4JPlXVgjiJ9dkZl0dK5rhlKUEoL/vg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n6ufle4xhy0fe6nkwp7yzfv7mxqdm06wtp2uj0dwzrtfv4rtzpfsmslgjn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQlplWXlXRWN2aXNLcHNQ
            QlF1TmdIVzBmU1RpVER2b2tPbDJ5eDRaeDAwCnVZSGJFSkthS2RZbHZmZmhFRks4
            aVdsbUVQTnBVbWVId3lXVUtsU2YxR2MKLS0tIFEya2UwTUdYYTFIVjltSnRSSnVp
            SzdOREI4bGRjdU8yV1RPTi9Lbk5wTzAKLMtQZ45Quaz2eyUz47es0KnK0lEn3q2t
            TKVqc2n8ZNOvPLd5/HhB8EUiDr32Pn71KmpPvqtLz6lcPC3kCZc50g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-14T23:51:24Z"
    mac: ENC[AES256_GCM,data:mSRqW9dcjcMdNRITfIHDQyoE1d7dXTsoULAKqD9hhfCrBo2gi1lVDfXDXHX2h5RgNvCaW2M/tu9JGK7/2GjB6J3vVZTTeggiORyILbE7EvZtpQpPRqEyB7+x7GU+aRToCd7h1rRlQGQZJjqPGdjjW7+pdOt2RJ6vrZJKE24mRLc=,iv:WUaDVDhNbgVy0WmtAKri8Lz04JkEEYjDKbnuClF22kM=,tag:cI6cIJPqadqjUx41DpLQ4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
