password: ENC[AES256_GCM,data:OJZziCeEkfS1mA==,iv:WH5bg5TTuzg+RVJsmwWHdZPG4y922Beycr1J+w0QmUI=,tag:e9rdC3nWVHQo56Y+HyrjIg==,type:str]
github_token: ENC[AES256_GCM,data:OcqDt+dqpjFVlrWmP5HDiIqjwp5rDBAbh5OjcEJ1jxkaT9p7kjgEB2WHS/mbOORIy5muJjhk87LoSZgHss6J4c2cm1oj+1c02k0OcrzrTlTFZt7Nnnfo/S9NtGMR,iv:Ma+fZ/CBSQ/5Q3OamWEjYs8isl5zO90G9R1WoXJtE0k=,tag:8chXvi7D1aDf2OpziPF7jQ==,type:str]
samba:
    smb_password: ENC[AES256_GCM,data:SBKvJVXQoaGxdVf50uRU,iv:KJagJzkuxX6FZO9IMAUeny/8slPUKUUYgJF9QRhhbR0=,tag:bmaiiBYAOBXFCMNSIl/vIg==,type:str]
    smb_username: ENC[AES256_GCM,data:ZQdu,iv:rJzv/1ovgzripHlRwuFuVeYxGObC6s54AhEWEmUM6IQ=,tag:ZnlYV7t7HhDZjNEu6hY0+Q==,type:str]
pia:
    pia_private_key: ENC[AES256_GCM,data:8H8oqtJePhmCQcp5UbbSDbgMNoWICFh58F+5RL7n4YjpNrETvavNUy0VvgI=,iv:lyfI3nvK9p+n+u+r96C31QB+94AHl3bRjMHct8rSjbM=,tag:I1bXB52YAVDxWEy9c7rdWg==,type:str]
sops:
    age:
        - recipient: age1wl25zsmys6cdzacrx4xh2fe89jk8enx4dalc52075kg9rdnuxf9qe2yw7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWXVDc0x1WFRIQzFMUWR1
            MmpNL21UNXMwQUx6UnlTOFpNRjIwamdxa2xFCkZ2aXhxdC9wdDBJbDhWZHpJZU9r
            a2RXV3htbm9mT09WblJHREpaemRzencKLS0tIEMwVm9OUDE0TDhCbzBSTHI3c081
            N2Z6RTlVRTdyb1ErcXNFbml4bGZiQkkKNMZQcGbE1YRWnwmrCTZMPf7uSsLHo+Np
            tkMcZhbkyeRNdAQ57zl2PaYApqcSNo244BgZ5bq8uLTHt771/uD6pQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dkwz3c2jprv8kz9e4r2yj5ugfsgx8hvmxc466k96d38c9hnuxp0s2u4qpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdm1FanhjWDhTLzZualJQ
            eEVXK2JleXQrMUtwWXZPY1UwbHRFYVM4Z0dzCm12b2oxdi9VWXhoOU5DQnpwOHRo
            THJubjVMQk1sL1UxN1h5SVV0dDZZanMKLS0tICtVRjZpOURpNEpNeXJVem8zTXpJ
            bUtUdi8xTHQyVEYyc294ZHBZOC9ZM2MKm66zjkaeIU094BWWH6gaM8ddEj9zmGbQ
            QnC275ywpUkwL/E0RyhQJJ1wD5IXXHuubdLHcDjc3I4+T4qbwNlR3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yuapchjs3ucvhftlv75t26m5vfyjdjjtrpmknvnk7cdy9n7jmf5sgvht94
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNE53WTdYeFF2dno3aE02
            RzV5RzdwMDZIMitubmhCZEhYd1B3YkYrUGlvCjFUZy9Zb3dCa2hFR0pQSUF3eENl
            UklaaWRVQXptUkg5cnpWbjFLSjVXTmMKLS0tIHd6N25makhBVnNGV3ZQMDZKOUdF
            RWluR3NzcTRnTTVhMDlPSzlCbklla2cKGtsQXVr+fASKmfbzYu4JcHlugCH5aOwZ
            PjyzsokNtGy7+cysjxBzvxwVrHgQvsR/qhrALknlRDJ+tDgHwR4N4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T07:48:40Z"
    mac: ENC[AES256_GCM,data:n7QE6xz/7gpNE7KmtwWy5Y+S1Ib61ZZ1v/cHVu2Q0k5YYCr/CsalhdFXetu7y32l9jExH9fOayOO5WEYn7LoVkJDZuQUXnlMnNgn22ufG9/WuueAtsx083GR/HYigfLGB/LKgAFTZcatGHVoEpWj2fvkheuF3pwHucN2uOt2Lgw=,iv:3P8sPMSA07xx9CANcAKlpd3HviLtWHSjobhe7y8Tk+Y=,tag:FpKd/r/1iVQv0ViGIDFrtA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
