# GENERATED by `nix run .#write-flake` -- do not edit by hand.
#
# Holds this layer's inputs and their lock, nothing else. The root reads
# this lock as DATA (lib/inputs.nix) and never calls `outputs`.
#
# Entries with no `follows` of their own are CARRIED: a `follows` cannot
# cross a flake boundary, so a name this layer only refers to still has
# to be declared here, pinned to its owner's locked rev. At merge those
# resolve to whichever source OWNS the name -- root or another layer --
# so the node below exists but is never the value anything resolves.
{
  outputs = _: { };

  inputs = {
    idris2Packages = {
      url = "github:mattpolzin/nix-idris2-packages";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nixpkgs = {
      url = "path:../../lib/stub";
      flake = false;
    };
    pnpm-nix-provider = {
      url = "github:wmertens/pnpm-nix-provider";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
}
