# This file is generated by `nix run .#write-flake`. To make changes, edit the
# `ff.*` declarations in the aspects listed under `packages` in ../../partition-map.nix.
#
# It exists only to hold inputs and their lock: the root flake reads
# `.inputs` out of it (see aspects/framework/partitions.nix) and never calls
# `outputs`. `nixpkgs` and every shared `follows` target are pinned to the
# root flake's locked rev so the two locks cannot drift; each is dropped
# again before the inputs are merged into the partition, and is here purely
# so the inputs below can `follows` it -- a `follows` cannot reach the
# parent flake.
{
  outputs = _: { };

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/6b5e5b7a6631f065bf6908986990b37d845f847f";
  };
}
